export type PortalLocale = "pt" | "en" | "es" | "it" | "sv";

const translations: Record<Exclude<PortalLocale, "pt">, Record<string, string>> = {
  en: {
    "post": "post", "posts": "posts", "Card do cliente": "Client post", "Banner do texto": "Text banner", "Hashtags do post": "Post hashtags",
    "etiqueta selecionada": "tag selected", "etiquetas selecionadas": "tags selected", "Cor da nova tag": "New tag color",
    "Aprovado pelo cliente": "Approved by client", "Pendente": "Pending", "Entrada": "Inbox", "Em Desenvolvimento": "In development", "Design pronto": "Design ready", "Enviar para Cliente": "Send to client",
    "Post único": "Single post", "Carrossel": "Carousel", "Reels": "Reels", "Stories": "Stories",
    "Portal do cliente": "Client portal", "Sugerir post": "Suggest a post", "Enviar uma ideia": "Send an idea",
    "Aprovações": "Approvals", "Textos": "Texts", "Aprovados": "Approved", "Pesquisa": "Search", "Arquivados": "Archived",
    "Faturas": "Invoices", "Relatórios": "Reports", "Alterar Senha": "Change password", "Trocar de conta": "Switch account",
    "Sair": "Sign out", "Senha atual": "Current password", "Nova senha": "New password", "Salvar nova senha": "Save new password",
    "Salvando...": "Saving...", "Senha atualizada com sucesso.": "Password updated successfully.", "Conta atual": "Current account",
    "Quadro do cliente": "Client board", "Calendário": "Calendar", "Pesquisar conteúdos": "Search content",
    "IDEIAS PARA REVISÃO": "IDEAS TO REVIEW", "Pautas para aprovação": "Topics for approval",
    "Revise a proposta, deixe um comentário e aprove para ela entrar no fluxo de criação.": "Review the proposal, leave a comment and approve it so it can enter the creation workflow.",
    "pauta": "topic", "pautas": "topics", "PAUTA": "TOPIC", "Proposta de conteúdo enviada para sua avaliação.": "Content proposal submitted for your review.",
    "Revisar": "Review", "CONTEÚDOS VISUAIS": "VISUAL CONTENT", "Posts para aprovação": "Posts for approval", "Em criação": "In creation",
    "Tudo revisado": "All reviewed", "Não há pautas ou posts aguardando sua aprovação agora.": "There are no topics or posts awaiting your approval right now.",
    "Próximos posts": "Upcoming posts", "Nenhum post agendado no momento.": "No posts are currently scheduled.",
    "Próximos compromissos": "Upcoming appointments", "Mensal": "Monthly",
    "O cliente encontra aqui os relatórios liberados por permissão, sem ver nada do restante da operação interna.": "Reports shared with this account appear here, without exposing the internal operation.",
    "Sugestão enviada. Ela já está no quadro da equipe com status pendente.": "Suggestion sent. It is now on the team's board with pending status.",
    "Enviado para Aprovados!": "Moved to Approved!", "Fechar aviso": "Close notification",
    "Seu feedback": "Your feedback", "Comente sobre este texto ou escolha uma ação para enviar seu retorno à equipe.": "Comment on this text or choose an action to send your feedback to the team.",
    "Escreva aqui seu comentário sobre este texto": "Write your comment about this text here", "Adicionar comentário": "Add comment",
    "Aprovar": "Approve", "Pedir alteração": "Request changes", "Enviando...": "Sending...", "Comentários": "Comments",
    "Nenhum texto foi enviado para sua área ainda.": "No text has been sent to your area yet.", "Comentário enviado.": "Comment sent.",
    "Texto aprovado com sucesso.": "Text approved successfully.", "Solicitação de alteração enviada.": "Change request sent.",
    "Financeiro": "Billing", "Consulte os lançamentos disponibilizados para sua conta.": "View the invoices available for your account.",
    "fatura": "invoice", "faturas": "invoices", "Emitida em": "Issued on", "Vencimento": "Due", "Paga": "Paid", "Atrasada": "Overdue",
    "Cancelada": "Cancelled", "Aberta": "Open", "Visualizar": "View", "Baixar": "Download", "Nenhuma fatura disponível": "No invoices available",
    "Quando uma fatura for liberada para esta conta, ela aparecerá aqui.": "When an invoice is released for this account, it will appear here.",
    "Visualização da fatura": "Invoice preview", "Fatura": "Invoice", "Fechar": "Close",
    "Conteúdos aprovados": "Approved content", "Visualize ou baixe as artes que já receberam aprovação.": "View or download the artwork that has already been approved.",
    "Consulte os posts que já receberam aprovação.": "View posts that have already been approved.", "Sem arte": "No artwork", "Aprovado": "Approved",
    "Consulte os posts e textos que já receberam aprovação.": "View posts and texts that have already been approved.", "Texto aprovado": "Approved text", "Visualizar texto": "View text", "Nenhum conteúdo aprovado ainda": "No approved content yet", "Quando um post ou texto for aprovado, ele aparecerá aqui para consulta.": "When a post or text is approved, it will appear here.",
    "arquivo disponível": "file available", "arquivos disponíveis": "files available", "Visualizar post": "View post", "Preparando download...": "Preparing download...",
    "Baixar tudo em ZIP": "Download all as ZIP", "Baixar conteúdo": "Download content", "Somente visualização": "View only",
    "Nenhum post aprovado ainda": "No approved posts yet", "Quando um post for aprovado, ele aparecerá aqui para consulta.": "When a post is approved, it will appear here.",
    "PESQUISA GLOBAL": "GLOBAL SEARCH", "Encontre qualquer conteúdo": "Find any content", "Pesquise posts em aprovação, aprovados, agendados ou arquivados.": "Search posts awaiting approval, approved, scheduled or archived.",
    "Busque por título ou palavra da legenda": "Search by title or caption keyword", "Buscando conteúdos...": "Searching content...", "Digite ao menos 2 letras para pesquisar": "Type at least 2 letters to search",
    "O que você procura?": "What are you looking for?", "Você pode pesquisar pelo título ou por qualquer trecho da legenda.": "You can search by title or any part of the caption.",
    "Nenhum conteúdo encontrado": "No content found", "Tente usar outra palavra ou uma parte menor do título.": "Try another word or a shorter part of the title.",
    "Sem legenda cadastrada.": "No caption added.", "Arquivado em": "Archived on", "Abrir post": "Open post", "resultado encontrado": "result found", "resultados encontrados": "results found",
    "Arquivado": "Archived", "Agendado": "Scheduled", "Alteração solicitada": "Changes requested", "Aguardando aprovação": "Awaiting approval",
    "ACOMPANHAMENTO": "TRACKING", "Tracker de conteúdo": "Content tracker", "Acompanhe cada etapa dos posts em produção.": "Follow every stage of the posts in production.",
    "concluído": "completed", "conteúdo no tracker": "item in tracker", "conteúdos no tracker": "items in tracker", "conteúdo concluído": "item completed", "conteúdos concluídos": "items completed",
    "em andamento": "in progress", "Em andamento": "In progress", "Nenhum conteúdo nesta etapa.": "No content at this stage.", "O tracker está pronto": "The tracker is ready",
    "Os conteúdos aparecerão aqui conforme forem liberados pela equipe.": "Content will appear here as it is released by the team.",
    "HISTÓRICO": "HISTORY", "Conteúdos arquivados": "Archived content", "Consulte os mesmos conteúdos arquivados no Kanban.": "View the same content archived on the Kanban board.",
    "conteúdo": "item", "conteúdos": "items", "Carregando conteúdos arquivados...": "Loading archived content...", "Nenhum conteúdo arquivado": "No archived content",
    "Quando um post for arquivado no Kanban, ele aparecerá aqui.": "When a post is archived on the Kanban board, it will appear here.", "Sem data": "No date", "Sem data registrada": "No date recorded",
    "Nova sugestão": "New suggestion", "Sugerir um post": "Suggest a post", "Envie sua ideia para a equipe. Ela ficará pendente até entrar no planejamento.": "Send your idea to the team. It will remain pending until it enters planning.",
    "Título da ideia *": "Idea title *", "Ex.: Carrossel com dúvidas frequentes": "E.g. Carousel with frequently asked questions", "Formato": "Format",
    "Descrição ou legenda": "Description or caption", "Conte a ideia, o objetivo e qualquer orientação para a equipe...": "Describe the idea, goal and any guidance for the team...",
    "Link de referência": "Reference link", "Artes ou referências": "Artwork or references", "arquivo selecionado": "file selected", "arquivos selecionados": "files selected",
    "Escolher arquivos": "Choose files", "Você pode enviar até 20 imagens ou vídeos.": "You can upload up to 20 images or videos.", "Cancelar": "Cancel",
    "Enviando sugestão...": "Sending suggestion...", "Enviar para a equipe": "Send to the team",
    "CONTEÚDO DO POST": "POST CONTENT", "Legenda": "Caption", "Editar legenda": "Edit caption", "Edite o texto abaixo": "Edit the text below",
    "Escreva a legenda do post...": "Write the post caption...", "caracteres": "characters", "Salvar legenda": "Save caption", "Sem legenda cadastrada ainda.": "No caption added yet.",
    "ETIQUETAS DO POST": "POST TAGS", "Nenhuma etiqueta": "No tags", "Gerenciar tags": "Manage tags", "Nenhuma tag criada. Crie a primeira abaixo.": "No tags created. Create the first one below.",
    "Nome da nova tag": "New tag name", "+ Criar": "+ Create", "Salvar etiquetas": "Save tags", "Status do cliente": "Client status", "Agendamento": "Schedule",
    "Não agendado": "Not scheduled", "comentário": "comment", "comentários": "comments", "Comente sobre este post ou escolha uma ação para enviar seu retorno à equipe.": "Comment on this post or choose an action to send your feedback to the team.",
    "Escreva aqui seu comentário sobre este post": "Write your comment about this post here", "Abrir link externo ↗": "Open external link ↗",
    "Comentário salvo.": "Comment saved.", "Card aprovado com sucesso.": "Post approved successfully.", "Não foi possível concluir a ação.": "Could not complete the action.",
    "Não foi possível preparar o download.": "Could not prepare the download.", "Não foi possível realizar a pesquisa.": "Could not complete the search.",
    "Mês anterior": "Previous month", "Próximo mês": "Next month", "Posts agendados": "Scheduled posts", "Compromissos": "Appointments",
    "Compromisso": "Appointment", "Sem detalhes adicionais.": "No additional details.", "Quando": "When", "VIDEOCHAMADA": "VIDEO CALL",
    "O link será aberto em uma nova aba.": "The link will open in a new tab.", "Entrar na reunião": "Join meeting",
    "PRIMEIRO ACESSO": "FIRST ACCESS", "Antes de começar, leia seu contrato": "Before you begin, read your contract",
    "este documento foi disponibilizado para sua conta. Revise os termos com calma.": "this document has been made available to your account. Please review the terms carefully.",
    "Ao clicar, você confirma que leu e está de acordo com os termos apresentados.": "By clicking, you confirm that you have read and agree to the terms presented.", "Li e aceito o contrato": "I have read and accept the contract",
  },
  es: {
    "Comentário enviado.": "Comentario enviado.", "Comentário salvo.": "Comentario guardado.", "Texto aprovado com sucesso.": "Texto aprobado correctamente.", "Solicitação de alteração enviada.": "Solicitud de cambios enviada.", "Card aprovado com sucesso.": "Publicación aprobada correctamente.", "Não foi possível concluir a ação.": "No se pudo completar la acción.", "Não foi possível preparar o download.": "No se pudo preparar la descarga.", "Não foi possível realizar a pesquisa.": "No se pudo realizar la búsqueda.", "Sugestão enviada. Ela já está no quadro da equipe com status pendente.": "Sugerencia enviada. Ya está en el tablero del equipo con estado pendiente.", "O cliente encontra aqui os relatórios liberados por permissão, sem ver nada do restante da operação interna.": "Aquí encontrarás los informes compartidos con tu cuenta, sin acceder a la operación interna.",
    "PRIMEIRO ACESSO": "PRIMER ACCESO", "Antes de começar, leia seu contrato": "Antes de comenzar, lee tu contrato", "este documento foi disponibilizado para sua conta. Revise os termos com calma.": "este documento está disponible para tu cuenta. Revisa los términos con atención.", "Ao clicar, você confirma que leu e está de acordo com os termos apresentados.": "Al hacer clic, confirmas que has leído y aceptas los términos presentados.", "Li e aceito o contrato": "He leído y acepto el contrato",
    "post": "publicación", "posts": "publicaciones", "Card do cliente": "Publicación del cliente", "Banner do texto": "Banner del texto", "Hashtags do post": "Hashtags de la publicación", "etiqueta selecionada": "etiqueta seleccionada", "etiquetas selecionadas": "etiquetas seleccionadas", "Cor da nova tag": "Color de la nueva etiqueta", "Aprovado pelo cliente": "Aprobado por el cliente", "Pendente": "Pendiente", "Entrada": "Entrada", "Em Desenvolvimento": "En desarrollo", "Design pronto": "Diseño listo", "Enviar para Cliente": "Enviar al cliente", "Post único": "Publicación única", "Carrossel": "Carrusel", "Reels": "Reels", "Stories": "Historias",
    "Portal do cliente": "Portal del cliente", "Sugerir post": "Sugerir una publicación", "Enviar uma ideia": "Enviar una idea", "Aprovações": "Aprobaciones", "Textos": "Textos", "Aprovados": "Aprobados", "Pesquisa": "Buscar", "Arquivados": "Archivados", "Faturas": "Facturas", "Relatórios": "Informes",
    "Alterar Senha": "Cambiar contraseña", "Trocar de conta": "Cambiar de cuenta", "Sair": "Cerrar sesión", "Senha atual": "Contraseña actual", "Nova senha": "Nueva contraseña", "Salvar nova senha": "Guardar nueva contraseña", "Salvando...": "Guardando...", "Senha atualizada com sucesso.": "Contraseña actualizada correctamente.", "Conta atual": "Cuenta actual",
    "Quadro do cliente": "Tablero del cliente", "Calendário": "Calendario", "Pesquisar conteúdos": "Buscar contenidos", "IDEIAS PARA REVISÃO": "IDEAS PARA REVISAR", "Pautas para aprovação": "Temas para aprobación", "Revise a proposta, deixe um comentário e aprove para ela entrar no fluxo de criação.": "Revisa la propuesta, deja un comentario y apruébala para que entre en el flujo de creación.", "pauta": "tema", "pautas": "temas", "PAUTA": "TEMA", "Proposta de conteúdo enviada para sua avaliação.": "Propuesta de contenido enviada para tu revisión.", "Revisar": "Revisar", "CONTEÚDOS VISUAIS": "CONTENIDOS VISUALES", "Posts para aprovação": "Publicaciones para aprobación", "Em criação": "En creación", "Tudo revisado": "Todo revisado", "Não há pautas ou posts aguardando sua aprovação agora.": "No hay temas ni publicaciones esperando tu aprobación.",
    "Próximos posts": "Próximas publicaciones", "Nenhum post agendado no momento.": "No hay publicaciones programadas.", "Próximos compromissos": "Próximas citas", "Mensal": "Mensual", "Enviado para Aprovados!": "¡Movido a Aprobados!", "Fechar aviso": "Cerrar aviso",
    "Seu feedback": "Tu opinión", "Comente sobre este texto ou escolha uma ação para enviar seu retorno à equipe.": "Comenta este texto o elige una acción para enviar tu opinión al equipo.", "Escreva aqui seu comentário sobre este texto": "Escribe aquí tu comentario sobre este texto", "Adicionar comentário": "Añadir comentario", "Aprovar": "Aprobar", "Pedir alteração": "Solicitar cambios", "Enviando...": "Enviando...", "Comentários": "Comentarios", "Nenhum texto foi enviado para sua área ainda.": "Aún no se ha enviado ningún texto a tu área.",
    "Financeiro": "Finanzas", "Consulte os lançamentos disponibilizados para sua conta.": "Consulta las facturas disponibles para tu cuenta.", "fatura": "factura", "faturas": "facturas", "Emitida em": "Emitida el", "Vencimento": "Vencimiento", "Paga": "Pagada", "Atrasada": "Vencida", "Cancelada": "Cancelada", "Aberta": "Abierta", "Visualizar": "Ver", "Baixar": "Descargar", "Nenhuma fatura disponível": "No hay facturas disponibles", "Quando uma fatura for liberada para esta conta, ela aparecerá aqui.": "Cuando se publique una factura para esta cuenta, aparecerá aquí.", "Visualização da fatura": "Vista previa de la factura", "Fatura": "Factura", "Fechar": "Cerrar",
    "Conteúdos aprovados": "Contenidos aprobados", "Visualize ou baixe as artes que já receberam aprovação.": "Consulta o descarga las artes ya aprobadas.", "Consulte os posts que já receberam aprovação.": "Consulta las publicaciones ya aprobadas.", "Consulte os posts e textos que já receberam aprovação.": "Consulta las publicaciones y los textos ya aprobados.", "Texto aprovado": "Texto aprobado", "Visualizar texto": "Ver texto", "Nenhum conteúdo aprovado ainda": "Aún no hay contenido aprobado", "Quando um post ou texto for aprovado, ele aparecerá aqui para consulta.": "Cuando se apruebe una publicación o un texto, aparecerá aquí.", "Sem arte": "Sin arte", "Aprovado": "Aprobado", "arquivo disponível": "archivo disponible", "arquivos disponíveis": "archivos disponibles", "Visualizar post": "Ver publicación", "Preparando download...": "Preparando descarga...", "Baixar tudo em ZIP": "Descargar todo en ZIP", "Baixar conteúdo": "Descargar contenido", "Somente visualização": "Solo visualización", "Nenhum post aprovado ainda": "Aún no hay publicaciones aprobadas", "Quando um post for aprovado, ele aparecerá aqui para consulta.": "Cuando se apruebe una publicación, aparecerá aquí.",
    "PESQUISA GLOBAL": "BÚSQUEDA GLOBAL", "Encontre qualquer conteúdo": "Encuentra cualquier contenido", "Pesquise posts em aprovação, aprovados, agendados ou arquivados.": "Busca publicaciones pendientes, aprobadas, programadas o archivadas.", "Busque por título ou palavra da legenda": "Busca por título o palabra del texto", "Buscando conteúdos...": "Buscando contenidos...", "Digite ao menos 2 letras para pesquisar": "Escribe al menos 2 letras", "O que você procura?": "¿Qué buscas?", "Você pode pesquisar pelo título ou por qualquer trecho da legenda.": "Puedes buscar por el título o cualquier parte del texto.", "Nenhum conteúdo encontrado": "No se encontró contenido", "Tente usar outra palavra ou uma parte menor do título.": "Prueba otra palabra o una parte más corta del título.", "Sem legenda cadastrada.": "Sin texto registrado.", "Arquivado em": "Archivado el", "Abrir post": "Abrir publicación", "resultado encontrado": "resultado encontrado", "resultados encontrados": "resultados encontrados",
    "Arquivado": "Archivado", "Agendado": "Programado", "Alteração solicitada": "Cambios solicitados", "Aguardando aprovação": "Pendiente de aprobación", "ACOMPANHAMENTO": "SEGUIMIENTO", "Tracker de conteúdo": "Seguimiento de contenidos", "Acompanhe cada etapa dos posts em produção.": "Sigue cada etapa de las publicaciones en producción.", "concluído": "completado", "conteúdo no tracker": "contenido en seguimiento", "conteúdos no tracker": "contenidos en seguimiento", "conteúdo concluído": "contenido completado", "conteúdos concluídos": "contenidos completados", "em andamento": "en curso", "Em andamento": "En curso", "Nenhum conteúdo nesta etapa.": "No hay contenido en esta etapa.", "O tracker está pronto": "El seguimiento está listo", "Os conteúdos aparecerão aqui conforme forem liberados pela equipe.": "Los contenidos aparecerán aquí cuando el equipo los publique.",
    "HISTÓRICO": "HISTORIAL", "Conteúdos arquivados": "Contenidos archivados", "Consulte os mesmos conteúdos arquivados no Kanban.": "Consulta los contenidos archivados en el Kanban.", "conteúdo": "contenido", "conteúdos": "contenidos", "Carregando conteúdos arquivados...": "Cargando contenidos archivados...", "Nenhum conteúdo arquivado": "No hay contenidos archivados", "Quando um post for arquivado no Kanban, ele aparecerá aqui.": "Cuando se archive una publicación, aparecerá aquí.", "Sem data": "Sin fecha", "Sem data registrada": "Sin fecha registrada",
    "Nova sugestão": "Nueva sugerencia", "Sugerir um post": "Sugerir una publicación", "Envie sua ideia para a equipe. Ela ficará pendente até entrar no planejamento.": "Envía tu idea al equipo. Quedará pendiente hasta entrar en la planificación.", "Título da ideia *": "Título de la idea *", "Ex.: Carrossel com dúvidas frequentes": "Ej.: Carrusel de preguntas frecuentes", "Formato": "Formato", "Descrição ou legenda": "Descripción o texto", "Conte a ideia, o objetivo e qualquer orientação para a equipe...": "Describe la idea, el objetivo y cualquier indicación para el equipo...", "Link de referência": "Enlace de referencia", "Artes ou referências": "Artes o referencias", "arquivo selecionado": "archivo seleccionado", "arquivos selecionados": "archivos seleccionados", "Escolher arquivos": "Elegir archivos", "Você pode enviar até 20 imagens ou vídeos.": "Puedes enviar hasta 20 imágenes o vídeos.", "Cancelar": "Cancelar", "Enviando sugestão...": "Enviando sugerencia...", "Enviar para a equipe": "Enviar al equipo",
    "CONTEÚDO DO POST": "CONTENIDO DE LA PUBLICACIÓN", "Legenda": "Texto", "Editar legenda": "Editar texto", "Edite o texto abaixo": "Edita el texto a continuación", "Escreva a legenda do post...": "Escribe el texto de la publicación...", "caracteres": "caracteres", "Salvar legenda": "Guardar texto", "Sem legenda cadastrada ainda.": "Aún no hay texto.", "ETIQUETAS DO POST": "ETIQUETAS DE LA PUBLICACIÓN", "Nenhuma etiqueta": "Sin etiquetas", "Gerenciar tags": "Gestionar etiquetas", "Nenhuma tag criada. Crie a primeira abaixo.": "No hay etiquetas. Crea la primera abajo.", "Nome da nova tag": "Nombre de la nueva etiqueta", "+ Criar": "+ Crear", "Salvar etiquetas": "Guardar etiquetas", "Status do cliente": "Estado del cliente", "Agendamento": "Programación", "Não agendado": "No programado", "comentário": "comentario", "comentários": "comentarios", "Comente sobre este post ou escolha uma ação para enviar seu retorno à equipe.": "Comenta esta publicación o elige una acción para enviar tu opinión al equipo.", "Escreva aqui seu comentário sobre este post": "Escribe aquí tu comentario sobre esta publicación", "Abrir link externo ↗": "Abrir enlace externo ↗",
    "Mês anterior": "Mes anterior", "Próximo mês": "Mes siguiente", "Posts agendados": "Publicaciones programadas", "Compromissos": "Citas", "Compromisso": "Cita", "Sem detalhes adicionais.": "Sin detalles adicionales.", "Quando": "Cuándo", "VIDEOCHAMADA": "VIDEOLLAMADA", "O link será aberto em uma nova aba.": "El enlace se abrirá en una nueva pestaña.", "Entrar na reunião": "Entrar a la reunión",
  },
  it: {
    "Comentário enviado.": "Commento inviato.", "Comentário salvo.": "Commento salvato.", "Texto aprovado com sucesso.": "Testo approvato.", "Solicitação de alteração enviada.": "Richiesta di modifica inviata.", "Card aprovado com sucesso.": "Post approvato.", "Não foi possível concluir a ação.": "Impossibile completare l'azione.", "Não foi possível preparar o download.": "Impossibile preparare il download.", "Não foi possível realizar a pesquisa.": "Impossibile completare la ricerca.", "Sugestão enviada. Ela já está no quadro da equipe com status pendente.": "Suggerimento inviato. Ora è nella bacheca del team in attesa.", "O cliente encontra aqui os relatórios liberados por permissão, sem ver nada do restante da operação interna.": "Qui trovi i report condivisi con il tuo account, senza accedere alle attività interne.",
    "PRIMEIRO ACESSO": "PRIMO ACCESSO", "Antes de começar, leia seu contrato": "Prima di iniziare, leggi il contratto", "este documento foi disponibilizado para sua conta. Revise os termos com calma.": "questo documento è disponibile per il tuo account. Leggi attentamente i termini.", "Ao clicar, você confirma que leu e está de acordo com os termos apresentados.": "Facendo clic, confermi di aver letto e accettato i termini presentati.", "Li e aceito o contrato": "Ho letto e accetto il contratto",
    "post": "post", "posts": "post", "Card do cliente": "Post del cliente", "Banner do texto": "Banner del testo", "Hashtags do post": "Hashtag del post", "etiqueta selecionada": "tag selezionato", "etiquetas selecionadas": "tag selezionati", "Cor da nova tag": "Colore del nuovo tag", "Aprovado pelo cliente": "Approvato dal cliente", "Pendente": "In attesa", "Entrada": "In ingresso", "Em Desenvolvimento": "In sviluppo", "Design pronto": "Design pronto", "Enviar para Cliente": "Invia al cliente", "Post único": "Post singolo", "Carrossel": "Carousel", "Reels": "Reel", "Stories": "Storie",
    "Portal do cliente": "Portale cliente", "Sugerir post": "Suggerisci un post", "Enviar uma ideia": "Invia un'idea", "Aprovações": "Approvazioni", "Textos": "Testi", "Aprovados": "Approvati", "Pesquisa": "Cerca", "Arquivados": "Archiviati", "Faturas": "Fatture", "Relatórios": "Report",
    "Alterar Senha": "Cambia password", "Trocar de conta": "Cambia account", "Sair": "Esci", "Senha atual": "Password attuale", "Nova senha": "Nuova password", "Salvar nova senha": "Salva nuova password", "Salvando...": "Salvataggio...", "Senha atualizada com sucesso.": "Password aggiornata.", "Conta atual": "Account attuale",
    "Quadro do cliente": "Bacheca cliente", "Calendário": "Calendario", "Pesquisar conteúdos": "Cerca contenuti", "IDEIAS PARA REVISÃO": "IDEE DA RIVEDERE", "Pautas para aprovação": "Argomenti da approvare", "Revise a proposta, deixe um comentário e aprove para ela entrar no fluxo de criação.": "Rivedi la proposta, lascia un commento e approvala per inserirla nel flusso creativo.", "pauta": "argomento", "pautas": "argomenti", "PAUTA": "ARGOMENTO", "Proposta de conteúdo enviada para sua avaliação.": "Proposta di contenuto inviata per la tua valutazione.", "Revisar": "Rivedi", "CONTEÚDOS VISUAIS": "CONTENUTI VISIVI", "Posts para aprovação": "Post da approvare", "Em criação": "In creazione", "Tudo revisado": "Tutto revisionato", "Não há pautas ou posts aguardando sua aprovação agora.": "Non ci sono argomenti o post in attesa di approvazione.",
    "Próximos posts": "Prossimi post", "Nenhum post agendado no momento.": "Nessun post programmato.", "Próximos compromissos": "Prossimi appuntamenti", "Mensal": "Mensile", "Enviado para Aprovados!": "Spostato in Approvati!", "Fechar aviso": "Chiudi avviso",
    "Seu feedback": "Il tuo feedback", "Comente sobre este texto ou escolha uma ação para enviar seu retorno à equipe.": "Commenta questo testo o scegli un'azione per inviare il feedback al team.", "Escreva aqui seu comentário sobre este texto": "Scrivi qui il tuo commento sul testo", "Adicionar comentário": "Aggiungi commento", "Aprovar": "Approva", "Pedir alteração": "Richiedi modifiche", "Enviando...": "Invio...", "Comentários": "Commenti", "Nenhum texto foi enviado para sua área ainda.": "Nessun testo è stato ancora inviato nella tua area.",
    "Financeiro": "Amministrazione", "Consulte os lançamentos disponibilizados para sua conta.": "Consulta le fatture disponibili per il tuo account.", "fatura": "fattura", "faturas": "fatture", "Emitida em": "Emessa il", "Vencimento": "Scadenza", "Paga": "Pagata", "Atrasada": "Scaduta", "Cancelada": "Annullata", "Aberta": "Aperta", "Visualizar": "Visualizza", "Baixar": "Scarica", "Nenhuma fatura disponível": "Nessuna fattura disponibile", "Quando uma fatura for liberada para esta conta, ela aparecerá aqui.": "Quando una fattura sarà disponibile, apparirà qui.", "Visualização da fatura": "Anteprima fattura", "Fatura": "Fattura", "Fechar": "Chiudi",
    "Conteúdos aprovados": "Contenuti approvati", "Visualize ou baixe as artes que já receberam aprovação.": "Visualizza o scarica le grafiche già approvate.", "Consulte os posts que já receberam aprovação.": "Consulta i post già approvati.", "Consulte os posts e textos que já receberam aprovação.": "Consulta i post e i testi già approvati.", "Texto aprovado": "Testo approvato", "Visualizar texto": "Visualizza testo", "Nenhum conteúdo aprovado ainda": "Nessun contenuto ancora approvato", "Quando um post ou texto for aprovado, ele aparecerá aqui para consulta.": "Quando un post o un testo sarà approvato, apparirà qui.", "Sem arte": "Senza grafica", "Aprovado": "Approvato", "arquivo disponível": "file disponibile", "arquivos disponíveis": "file disponibili", "Visualizar post": "Visualizza post", "Preparando download...": "Preparazione download...", "Baixar tudo em ZIP": "Scarica tutto in ZIP", "Baixar conteúdo": "Scarica contenuto", "Somente visualização": "Solo visualizzazione", "Nenhum post aprovado ainda": "Nessun post ancora approvato", "Quando um post for aprovado, ele aparecerá aqui para consulta.": "Quando un post sarà approvato, apparirà qui.",
    "PESQUISA GLOBAL": "RICERCA GLOBALE", "Encontre qualquer conteúdo": "Trova qualsiasi contenuto", "Pesquise posts em aprovação, aprovados, agendados ou arquivados.": "Cerca post da approvare, approvati, programmati o archiviati.", "Busque por título ou palavra da legenda": "Cerca per titolo o parola della didascalia", "Buscando conteúdos...": "Ricerca contenuti...", "Digite ao menos 2 letras para pesquisar": "Digita almeno 2 lettere", "O que você procura?": "Cosa stai cercando?", "Você pode pesquisar pelo título ou por qualquer trecho da legenda.": "Puoi cercare per titolo o parte della didascalia.", "Nenhum conteúdo encontrado": "Nessun contenuto trovato", "Tente usar outra palavra ou uma parte menor do título.": "Prova un'altra parola o una parte più breve del titolo.", "Sem legenda cadastrada.": "Nessuna didascalia.", "Arquivado em": "Archiviato il", "Abrir post": "Apri post", "resultado encontrado": "risultato trovato", "resultados encontrados": "risultati trovati",
    "Arquivado": "Archiviato", "Agendado": "Programmato", "Alteração solicitada": "Modifiche richieste", "Aguardando aprovação": "In attesa di approvazione", "ACOMPANHAMENTO": "MONITORAGGIO", "Tracker de conteúdo": "Monitoraggio contenuti", "Acompanhe cada etapa dos posts em produção.": "Segui ogni fase dei post in produzione.", "concluído": "completato", "conteúdo no tracker": "contenuto nel tracker", "conteúdos no tracker": "contenuti nel tracker", "conteúdo concluído": "contenuto completato", "conteúdos concluídos": "contenuti completati", "em andamento": "in corso", "Em andamento": "In corso", "Nenhum conteúdo nesta etapa.": "Nessun contenuto in questa fase.", "O tracker está pronto": "Il tracker è pronto", "Os conteúdos aparecerão aqui conforme forem liberados pela equipe.": "I contenuti appariranno qui quando saranno pubblicati dal team.",
    "HISTÓRICO": "CRONOLOGIA", "Conteúdos arquivados": "Contenuti archiviati", "Consulte os mesmos conteúdos arquivados no Kanban.": "Consulta i contenuti archiviati nel Kanban.", "conteúdo": "contenuto", "conteúdos": "contenuti", "Carregando conteúdos arquivados...": "Caricamento contenuti archiviati...", "Nenhum conteúdo arquivado": "Nessun contenuto archiviato", "Quando um post for arquivado no Kanban, ele aparecerá aqui.": "Quando un post sarà archiviato, apparirà qui.", "Sem data": "Senza data", "Sem data registrada": "Nessuna data registrata",
    "Nova sugestão": "Nuovo suggerimento", "Sugerir um post": "Suggerisci un post", "Envie sua ideia para a equipe. Ela ficará pendente até entrar no planejamento.": "Invia la tua idea al team. Rimarrà in attesa fino alla pianificazione.", "Título da ideia *": "Titolo dell'idea *", "Ex.: Carrossel com dúvidas frequentes": "Es.: Carousel con domande frequenti", "Formato": "Formato", "Descrição ou legenda": "Descrizione o didascalia", "Conte a ideia, o objetivo e qualquer orientação para a equipe...": "Descrivi l'idea, l'obiettivo e le indicazioni per il team...", "Link de referência": "Link di riferimento", "Artes ou referências": "Grafiche o riferimenti", "arquivo selecionado": "file selezionato", "arquivos selecionados": "file selezionati", "Escolher arquivos": "Scegli file", "Você pode enviar até 20 imagens ou vídeos.": "Puoi inviare fino a 20 immagini o video.", "Cancelar": "Annulla", "Enviando sugestão...": "Invio suggerimento...", "Enviar para a equipe": "Invia al team",
    "CONTEÚDO DO POST": "CONTENUTO DEL POST", "Legenda": "Didascalia", "Editar legenda": "Modifica didascalia", "Edite o texto abaixo": "Modifica il testo qui sotto", "Escreva a legenda do post...": "Scrivi la didascalia del post...", "caracteres": "caratteri", "Salvar legenda": "Salva didascalia", "Sem legenda cadastrada ainda.": "Nessuna didascalia.", "ETIQUETAS DO POST": "TAG DEL POST", "Nenhuma etiqueta": "Nessun tag", "Gerenciar tags": "Gestisci tag", "Nenhuma tag criada. Crie a primeira abaixo.": "Nessun tag creato. Crea il primo qui sotto.", "Nome da nova tag": "Nome del nuovo tag", "+ Criar": "+ Crea", "Salvar etiquetas": "Salva tag", "Status do cliente": "Stato cliente", "Agendamento": "Programmazione", "Não agendado": "Non programmato", "comentário": "commento", "comentários": "commenti", "Comente sobre este post ou escolha uma ação para enviar seu retorno à equipe.": "Commenta questo post o scegli un'azione per inviare il feedback al team.", "Escreva aqui seu comentário sobre este post": "Scrivi qui il tuo commento sul post", "Abrir link externo ↗": "Apri link esterno ↗",
    "Mês anterior": "Mese precedente", "Próximo mês": "Mese successivo", "Posts agendados": "Post programmati", "Compromissos": "Appuntamenti", "Compromisso": "Appuntamento", "Sem detalhes adicionais.": "Nessun dettaglio aggiuntivo.", "Quando": "Quando", "VIDEOCHAMADA": "VIDEOCHIAMATA", "O link será aberto em uma nova aba.": "Il link si aprirà in una nuova scheda.", "Entrar na reunião": "Partecipa alla riunione",
  },
  sv: {
    "Comentário enviado.": "Kommentaren har skickats.", "Comentário salvo.": "Kommentaren har sparats.", "Texto aprovado com sucesso.": "Texten har godkänts.", "Solicitação de alteração enviada.": "Ändringsbegäran har skickats.", "Card aprovado com sucesso.": "Inlägget har godkänts.", "Não foi possível concluir a ação.": "Åtgärden kunde inte slutföras.", "Não foi possível preparar o download.": "Nedladdningen kunde inte förberedas.", "Não foi possível realizar a pesquisa.": "Sökningen kunde inte genomföras.", "Sugestão enviada. Ela já está no quadro da equipe com status pendente.": "Förslaget har skickats och finns nu på teamets tavla med väntande status.", "O cliente encontra aqui os relatórios liberados por permissão, sem ver nada do restante da operação interna.": "Här visas rapporter som delats med ditt konto, utan åtkomst till den interna verksamheten.",
    "PRIMEIRO ACESSO": "FÖRSTA INLOGGNINGEN", "Antes de começar, leia seu contrato": "Läs ditt avtal innan du börjar", "este documento foi disponibilizado para sua conta. Revise os termos com calma.": "detta dokument har gjorts tillgängligt för ditt konto. Läs villkoren noggrant.", "Ao clicar, você confirma que leu e está de acordo com os termos apresentados.": "Genom att klicka bekräftar du att du har läst och godkänner villkoren.", "Li e aceito o contrato": "Jag har läst och godkänner avtalet",
    "post": "inlägg", "posts": "inlägg", "Card do cliente": "Kundinlägg", "Banner do texto": "Textbanner", "Hashtags do post": "Inläggets hashtaggar", "etiqueta selecionada": "tagg vald", "etiquetas selecionadas": "taggar valda", "Cor da nova tag": "Färg på ny tagg", "Aprovado pelo cliente": "Godkänt av kunden", "Pendente": "Väntar", "Entrada": "Inkorg", "Em Desenvolvimento": "Under utveckling", "Design pronto": "Design klar", "Enviar para Cliente": "Skicka till kund", "Post único": "Enskilt inlägg", "Carrossel": "Karusell", "Reels": "Reels", "Stories": "Stories",
    "Portal do cliente": "Kundportal", "Sugerir post": "Föreslå ett inlägg", "Enviar uma ideia": "Skicka en idé", "Aprovações": "Godkännanden", "Textos": "Texter", "Aprovados": "Godkända", "Pesquisa": "Sök", "Arquivados": "Arkiverade", "Faturas": "Fakturor", "Relatórios": "Rapporter",
    "Alterar Senha": "Byt lösenord", "Trocar de conta": "Byt konto", "Sair": "Logga ut", "Senha atual": "Nuvarande lösenord", "Nova senha": "Nytt lösenord", "Salvar nova senha": "Spara nytt lösenord", "Salvando...": "Sparar...", "Senha atualizada com sucesso.": "Lösenordet har uppdaterats.", "Conta atual": "Nuvarande konto",
    "Quadro do cliente": "Kundens tavla", "Calendário": "Kalender", "Pesquisar conteúdos": "Sök innehåll", "IDEIAS PARA REVISÃO": "IDÉER ATT GRANSKA", "Pautas para aprovação": "Ämnen för godkännande", "Revise a proposta, deixe um comentário e aprove para ela entrar no fluxo de criação.": "Granska förslaget, lämna en kommentar och godkänn det för att föra in det i arbetsflödet.", "pauta": "ämne", "pautas": "ämnen", "PAUTA": "ÄMNE", "Proposta de conteúdo enviada para sua avaliação.": "Innehållsförslag skickat för din granskning.", "Revisar": "Granska", "CONTEÚDOS VISUAIS": "VISUELLT INNEHÅLL", "Posts para aprovação": "Inlägg för godkännande", "Em criação": "Under produktion", "Tudo revisado": "Allt granskat", "Não há pautas ou posts aguardando sua aprovação agora.": "Det finns inga ämnen eller inlägg som väntar på ditt godkännande.",
    "Próximos posts": "Kommande inlägg", "Nenhum post agendado no momento.": "Inga inlägg är schemalagda.", "Próximos compromissos": "Kommande möten", "Mensal": "Månadsvis", "Enviado para Aprovados!": "Flyttat till Godkända!", "Fechar aviso": "Stäng meddelandet",
    "Seu feedback": "Din feedback", "Comente sobre este texto ou escolha uma ação para enviar seu retorno à equipe.": "Kommentera texten eller välj en åtgärd för att skicka din feedback till teamet.", "Escreva aqui seu comentário sobre este texto": "Skriv din kommentar om texten här", "Adicionar comentário": "Lägg till kommentar", "Aprovar": "Godkänn", "Pedir alteração": "Begär ändringar", "Enviando...": "Skickar...", "Comentários": "Kommentarer", "Nenhum texto foi enviado para sua área ainda.": "Ingen text har skickats till ditt område ännu.",
    "Financeiro": "Ekonomi", "Consulte os lançamentos disponibilizados para sua conta.": "Se fakturorna som är tillgängliga för ditt konto.", "fatura": "faktura", "faturas": "fakturor", "Emitida em": "Utfärdad", "Vencimento": "Förfallodatum", "Paga": "Betald", "Atrasada": "Förfallen", "Cancelada": "Annullerad", "Aberta": "Öppen", "Visualizar": "Visa", "Baixar": "Ladda ner", "Nenhuma fatura disponível": "Inga fakturor tillgängliga", "Quando uma fatura for liberada para esta conta, ela aparecerá aqui.": "När en faktura görs tillgänglig visas den här.", "Visualização da fatura": "Förhandsgranska faktura", "Fatura": "Faktura", "Fechar": "Stäng",
    "Conteúdos aprovados": "Godkänt innehåll", "Visualize ou baixe as artes que já receberam aprovação.": "Visa eller ladda ner material som redan har godkänts.", "Consulte os posts que já receberam aprovação.": "Visa inlägg som redan har godkänts.", "Consulte os posts e textos que já receberam aprovação.": "Visa inlägg och texter som redan har godkänts.", "Texto aprovado": "Godkänd text", "Visualizar texto": "Visa text", "Nenhum conteúdo aprovado ainda": "Inget godkänt innehåll ännu", "Quando um post ou texto for aprovado, ele aparecerá aqui para consulta.": "När ett inlägg eller en text godkänns visas det här.", "Sem arte": "Inget material", "Aprovado": "Godkänt", "arquivo disponível": "fil tillgänglig", "arquivos disponíveis": "filer tillgängliga", "Visualizar post": "Visa inlägg", "Preparando download...": "Förbereder nedladdning...", "Baixar tudo em ZIP": "Ladda ner allt som ZIP", "Baixar conteúdo": "Ladda ner innehåll", "Somente visualização": "Endast visning", "Nenhum post aprovado ainda": "Inga godkända inlägg ännu", "Quando um post for aprovado, ele aparecerá aqui para consulta.": "När ett inlägg godkänns visas det här.",
    "PESQUISA GLOBAL": "GLOBAL SÖKNING", "Encontre qualquer conteúdo": "Hitta valfritt innehåll", "Pesquise posts em aprovação, aprovados, agendados ou arquivados.": "Sök bland väntande, godkända, schemalagda eller arkiverade inlägg.", "Busque por título ou palavra da legenda": "Sök efter titel eller ord i texten", "Buscando conteúdos...": "Söker innehåll...", "Digite ao menos 2 letras para pesquisar": "Skriv minst 2 bokstäver", "O que você procura?": "Vad letar du efter?", "Você pode pesquisar pelo título ou por qualquer trecho da legenda.": "Du kan söka efter titeln eller valfri del av texten.", "Nenhum conteúdo encontrado": "Inget innehåll hittades", "Tente usar outra palavra ou uma parte menor do título.": "Prova ett annat ord eller en kortare del av titeln.", "Sem legenda cadastrada.": "Ingen text tillagd.", "Arquivado em": "Arkiverad", "Abrir post": "Öppna inlägg", "resultado encontrado": "resultat hittat", "resultados encontrados": "resultat hittades",
    "Arquivado": "Arkiverad", "Agendado": "Schemalagd", "Alteração solicitada": "Ändringar begärda", "Aguardando aprovação": "Väntar på godkännande", "ACOMPANHAMENTO": "UPPFÖLJNING", "Tracker de conteúdo": "Innehållsuppföljning", "Acompanhe cada etapa dos posts em produção.": "Följ varje steg för inlägg i produktion.", "concluído": "klart", "conteúdo no tracker": "innehåll i uppföljning", "conteúdos no tracker": "innehåll i uppföljning", "conteúdo concluído": "innehåll klart", "conteúdos concluídos": "innehåll klara", "em andamento": "pågår", "Em andamento": "Pågår", "Nenhum conteúdo nesta etapa.": "Inget innehåll i detta steg.", "O tracker está pronto": "Uppföljningen är klar", "Os conteúdos aparecerão aqui conforme forem liberados pela equipe.": "Innehåll visas här när teamet publicerar det.",
    "HISTÓRICO": "HISTORIK", "Conteúdos arquivados": "Arkiverat innehåll", "Consulte os mesmos conteúdos arquivados no Kanban.": "Visa samma innehåll som arkiverats på Kanban-tavlan.", "conteúdo": "innehåll", "conteúdos": "innehåll", "Carregando conteúdos arquivados...": "Laddar arkiverat innehåll...", "Nenhum conteúdo arquivado": "Inget arkiverat innehåll", "Quando um post for arquivado no Kanban, ele aparecerá aqui.": "När ett inlägg arkiveras visas det här.", "Sem data": "Inget datum", "Sem data registrada": "Inget datum registrerat",
    "Nova sugestão": "Nytt förslag", "Sugerir um post": "Föreslå ett inlägg", "Envie sua ideia para a equipe. Ela ficará pendente até entrar no planejamento.": "Skicka din idé till teamet. Den väntar tills den tas in i planeringen.", "Título da ideia *": "Idéns titel *", "Ex.: Carrossel com dúvidas frequentes": "T.ex. karusell med vanliga frågor", "Formato": "Format", "Descrição ou legenda": "Beskrivning eller text", "Conte a ideia, o objetivo e qualquer orientação para a equipe...": "Beskriv idén, målet och eventuella instruktioner till teamet...", "Link de referência": "Referenslänk", "Artes ou referências": "Material eller referenser", "arquivo selecionado": "fil vald", "arquivos selecionados": "filer valda", "Escolher arquivos": "Välj filer", "Você pode enviar até 20 imagens ou vídeos.": "Du kan ladda upp upp till 20 bilder eller videor.", "Cancelar": "Avbryt", "Enviando sugestão...": "Skickar förslag...", "Enviar para a equipe": "Skicka till teamet",
    "CONTEÚDO DO POST": "INLÄGGETS INNEHÅLL", "Legenda": "Text", "Editar legenda": "Redigera text", "Edite o texto abaixo": "Redigera texten nedan", "Escreva a legenda do post...": "Skriv inläggets text...", "caracteres": "tecken", "Salvar legenda": "Spara text", "Sem legenda cadastrada ainda.": "Ingen text tillagd ännu.", "ETIQUETAS DO POST": "INLÄGGETS TAGGAR", "Nenhuma etiqueta": "Inga taggar", "Gerenciar tags": "Hantera taggar", "Nenhuma tag criada. Crie a primeira abaixo.": "Inga taggar skapade. Skapa den första nedan.", "Nome da nova tag": "Namn på ny tagg", "+ Criar": "+ Skapa", "Salvar etiquetas": "Spara taggar", "Status do cliente": "Kundstatus", "Agendamento": "Schemaläggning", "Não agendado": "Inte schemalagd", "comentário": "kommentar", "comentários": "kommentarer", "Comente sobre este post ou escolha uma ação para enviar seu retorno à equipe.": "Kommentera inlägget eller välj en åtgärd för att skicka feedback till teamet.", "Escreva aqui seu comentário sobre este post": "Skriv din kommentar om inlägget här", "Abrir link externo ↗": "Öppna extern länk ↗",
    "Mês anterior": "Föregående månad", "Próximo mês": "Nästa månad", "Posts agendados": "Schemalagda inlägg", "Compromissos": "Möten", "Compromisso": "Möte", "Sem detalhes adicionais.": "Inga ytterligare detaljer.", "Quando": "När", "VIDEOCHAMADA": "VIDEOSAMTAL", "O link será aberto em uma nova aba.": "Länken öppnas i en ny flik.", "Entrar na reunião": "Gå med i mötet",
  },
};

const brandBrainTranslations: Record<Exclude<PortalLocale, "pt">, Record<string, string>> = {
  en: {
    "Não foi possível atualizar a senha.": "Could not update the password.", "Não foi possível carregar os arquivados.": "Could not load archived content.", "Não foi possível enviar o retorno.": "Could not send your feedback.", "Não foi possível enviar a sugestão.": "Could not send the suggestion.", "Não foi possível salvar a legenda.": "Could not save the caption.", "Não foi possível criar a etiqueta.": "Could not create the tag.", "Não foi possível salvar as etiquetas.": "Could not save the tags.",
    "Organizando a memória da marca…": "Organizing the brand memory…", "Não foi possível carregar o Brand Brain.": "Could not load the Brand Brain.", "Ainda não publicado": "Not published yet", "A fonte de verdade da marca para estratégia, conteúdo e direção visual.": "The single source of truth for the brand's strategy, content and visual direction.", "Versão": "Version", "inicial": "initial", "Atualizado": "Updated", "sugestão pendente": "pending suggestion", "sugestões pendentes": "pending suggestions", "Tudo alinhado": "Everything aligned", "da identidade preenchida": "of the identity completed", "Visão geral": "Overview", "Essência": "Essence", "Público": "Audience", "Voz": "Voice", "Conteúdo": "Content", "Visual": "Visual", "Histórico": "History",
    "Missão": "Mission", "Visão": "Vision", "Posicionamento": "Positioning", "Promessa da marca": "Brand promise", "Diferenciais": "Differentiators", "Provas e credenciais": "Proof and credentials", "Público prioritário": "Primary audience", "Dores e tensões": "Pain points and tensions", "Desejos e objetivos": "Desires and goals", "Tom de voz": "Tone of voice", "Traços de personalidade": "Personality traits", "Exemplos de como falar": "Examples of how to speak", "Exemplos de como não falar": "Examples of how not to speak", "Vocabulário preferido": "Preferred vocabulary", "Expressões da marca": "Brand expressions", "Termos a evitar": "Terms to avoid", "Direção visual": "Visual direction", "Cores da marca": "Brand colors", "Fonte de destaque": "Display font", "Fonte de texto": "Body font", "Fonte de apoio": "Accent font", "Texto de demonstração": "Sample text", "Referências": "References", "Um item por linha": "One item per line",
    "VERIFICAÇÃO DE CONTEÚDO": "CONTENT CHECK", "Teste uma legenda": "Test a caption", "Cole o texto para conferir se ele conversa com a memória da marca.": "Paste text to check whether it matches the brand memory.", "Cole aqui a legenda ou o texto que deseja revisar…": "Paste the caption or text you want to review here…", "Ajustar": "Adjust", "Tudo certo": "All good", "Nenhum termo proibido encontrado.": "No prohibited terms found.", "Vocabulário": "Vocabulary", "Nenhuma expressão característica apareceu ainda.": "No characteristic expression has appeared yet.", "Pilar relacionado": "Related pillar", "Não identificamos conexão clara com um pilar.": "No clear connection to a pillar was found.", "Tom esperado": "Expected tone", "Defina o tom de voz para receber uma orientação mais completa.": "Define the tone of voice to receive more complete guidance.", "A análise acontece enquanto você escreve, sem alterar o conteúdo original.": "The analysis runs as you type without changing the original content.",
    "Sugestão enviada para a equipe. Ela ficará pendente até a aprovação.": "Suggestion sent to the team. It will remain pending until approved.", "Brand Brain atualizado e uma nova versão foi registrada.": "Brand Brain updated and a new version was recorded.", "Não foi possível salvar.": "Could not save.", "Não foi possível comentar.": "Could not add the comment."
    , "POSICIONAMENTO": "POSITIONING", "Defina o espaço único que a marca deseja ocupar.": "Define the unique place the brand should occupy.", "A promessa central da marca aparecerá aqui.": "The brand's central promise will appear here.", "VOZ · PERSONALIDADE": "VOICE · PERSONALITY", "Defina como a marca fala e se relaciona.": "Define how the brand speaks and connects.", "Abrir →": "Open →", "PILARES": "PILLARS", "pilar": "pillar", "pilares": "pillars", "Nenhum pilar definido ainda.": "No pillars defined yet.", "VISUAL": "VISUAL", "Paleta": "Palette", "Tipografia": "Typography", "Tipografia ainda não definida": "Typography not defined yet", "Explore as seções": "Explore the sections", "Pilares: nome | foco | peso": "Pillars: name | focus | weight", "Um pilar por linha. Ex.: Educação | Ensinar com clareza | 40": "One pillar per line. E.g.: Education | Teach clearly | 40", "Use códigos hexadecimais separados por vírgula.": "Use comma-separated hexadecimal codes.", "PRÉVIA TIPOGRÁFICA": "TYPOGRAPHY PREVIEW", "Defina as fontes acima": "Define the fonts above", "Título principal da marca": "Main brand heading", "Detalhe ou assinatura em": "Detail or signature in", "Sua sugestão está em análise": "Your suggestion is under review", "A equipe recebeu a atualização e você verá a nova versão aqui assim que ela for aprovada.": "The team received the update. The new version will appear here once approved.", "Versões publicadas": "Published versions", "A primeira versão será criada no próximo salvamento.": "The first version will be created on the next save.", "Rascunho protegido": "Draft protected", "CONVERSA DA MARCA": "BRAND CONVERSATION"
  },
  es: {
    "Não foi possível atualizar a senha.": "No se pudo actualizar la contraseña.", "Não foi possível carregar os arquivados.": "No se pudo cargar el contenido archivado.", "Não foi possível enviar o retorno.": "No se pudo enviar tu comentario.", "Não foi possível enviar a sugestão.": "No se pudo enviar la sugerencia.", "Não foi possível salvar a legenda.": "No se pudo guardar el texto.", "Não foi possível criar a etiqueta.": "No se pudo crear la etiqueta.", "Não foi possível salvar as etiquetas.": "No se pudieron guardar las etiquetas.",
    "Organizando a memória da marca…": "Organizando la memoria de marca…", "Não foi possível carregar o Brand Brain.": "No se pudo cargar el Brand Brain.", "Ainda não publicado": "Aún no publicado", "A fonte de verdade da marca para estratégia, conteúdo e direção visual.": "La fuente central de la estrategia, el contenido y la dirección visual de la marca.", "Versão": "Versión", "inicial": "inicial", "Atualizado": "Actualizado", "sugestão pendente": "sugerencia pendiente", "sugestões pendentes": "sugerencias pendientes", "Tudo alinhado": "Todo alineado", "da identidade preenchida": "de la identidad completada", "Visão geral": "Vista general", "Essência": "Esencia", "Público": "Público", "Voz": "Voz", "Conteúdo": "Contenido", "Visual": "Visual", "Histórico": "Historial",
    "Missão": "Misión", "Visão": "Visión", "Posicionamento": "Posicionamiento", "Promessa da marca": "Promesa de marca", "Diferenciais": "Diferenciales", "Provas e credenciais": "Pruebas y credenciales", "Público prioritário": "Público prioritario", "Dores e tensões": "Dolores y tensiones", "Desejos e objetivos": "Deseos y objetivos", "Tom de voz": "Tono de voz", "Traços de personalidade": "Rasgos de personalidad", "Exemplos de como falar": "Ejemplos de cómo hablar", "Exemplos de como não falar": "Ejemplos de cómo no hablar", "Vocabulário preferido": "Vocabulario preferido", "Expressões da marca": "Expresiones de marca", "Termos a evitar": "Términos a evitar", "Direção visual": "Dirección visual", "Cores da marca": "Colores de marca", "Fonte de destaque": "Tipografía destacada", "Fonte de texto": "Tipografía de texto", "Fonte de apoio": "Tipografía de apoyo", "Texto de demonstração": "Texto de muestra", "Referências": "Referencias", "Um item por linha": "Un elemento por línea",
    "VERIFICAÇÃO DE CONTEÚDO": "VERIFICACIÓN DE CONTENIDO", "Teste uma legenda": "Prueba un texto", "Cole o texto para conferir se ele conversa com a memória da marca.": "Pega el texto para comprobar si coincide con la memoria de marca.", "Cole aqui a legenda ou o texto que deseja revisar…": "Pega aquí el texto que deseas revisar…", "Ajustar": "Ajustar", "Tudo certo": "Todo correcto", "Nenhum termo proibido encontrado.": "No se encontraron términos prohibidos.", "Vocabulário": "Vocabulario", "Pilar relacionado": "Pilar relacionado", "Nenhuma expressão característica apareceu ainda.": "Todavía no aparece ninguna expresión característica.", "Não identificamos conexão clara com um pilar.": "No se identificó una conexión clara con un pilar.", "Tom esperado": "Tono esperado", "Defina o tom de voz para receber uma orientação mais completa.": "Define el tono de voz para recibir una orientación más completa.", "A análise acontece enquanto você escreve, sem alterar o conteúdo original.": "El análisis se realiza mientras escribes, sin cambiar el contenido original.", "Sugestão enviada para a equipe. Ela ficará pendente até a aprovação.": "Sugerencia enviada al equipo. Quedará pendiente hasta su aprobación.", "Brand Brain atualizado e uma nova versão foi registrada.": "Brand Brain actualizado y nueva versión registrada.", "Não foi possível salvar.": "No se pudo guardar.", "Não foi possível comentar.": "No se pudo añadir el comentario."
    , "POSICIONAMENTO": "POSICIONAMIENTO", "Defina o espaço único que a marca deseja ocupar.": "Define el espacio único que la marca desea ocupar.", "A promessa central da marca aparecerá aqui.": "La promesa central de la marca aparecerá aquí.", "VOZ · PERSONALIDADE": "VOZ · PERSONALIDAD", "Defina como a marca fala e se relaciona.": "Define cómo habla y se relaciona la marca.", "Abrir →": "Abrir →", "PILARES": "PILARES", "pilar": "pilar", "pilares": "pilares", "Nenhum pilar definido ainda.": "Aún no hay pilares definidos.", "VISUAL": "VISUAL", "Paleta": "Paleta", "Tipografia": "Tipografía", "Tipografia ainda não definida": "Tipografía aún no definida", "Explore as seções": "Explora las secciones", "Pilares: nome | foco | peso": "Pilares: nombre | enfoque | peso", "Um pilar por linha. Ex.: Educação | Ensinar com clareza | 40": "Un pilar por línea. Ej.: Educación | Enseñar con claridad | 40", "Use códigos hexadecimais separados por vírgula.": "Usa códigos hexadecimales separados por comas.", "PRÉVIA TIPOGRÁFICA": "VISTA PREVIA TIPOGRÁFICA", "Defina as fontes acima": "Define las tipografías arriba", "Título principal da marca": "Título principal de la marca", "Detalhe ou assinatura em": "Detalle o firma en", "Sua sugestão está em análise": "Tu sugerencia está en revisión", "A equipe recebeu a atualização e você verá a nova versão aqui assim que ela for aprovada.": "El equipo recibió la actualización. Verás aquí la nueva versión cuando sea aprobada.", "Versões publicadas": "Versiones publicadas", "A primeira versão será criada no próximo salvamento.": "La primera versión se creará al guardar de nuevo.", "Rascunho protegido": "Borrador protegido", "CONVERSA DA MARCA": "CONVERSACIÓN DE MARCA"
  },
  it: {
    "Não foi possível atualizar a senha.": "Impossibile aggiornare la password.", "Não foi possível carregar os arquivados.": "Impossibile caricare i contenuti archiviati.", "Não foi possível enviar o retorno.": "Impossibile inviare il feedback.", "Não foi possível enviar a sugestão.": "Impossibile inviare il suggerimento.", "Não foi possível salvar a legenda.": "Impossibile salvare la didascalia.", "Não foi possível criar a etiqueta.": "Impossibile creare il tag.", "Não foi possível salvar as etiquetas.": "Impossibile salvare i tag.",
    "Organizando a memória da marca…": "Organizzazione della memoria del brand…", "Não foi possível carregar o Brand Brain.": "Impossibile caricare il Brand Brain.", "Ainda não publicado": "Non ancora pubblicato", "A fonte de verdade da marca para estratégia, conteúdo e direção visual.": "La fonte centrale per strategia, contenuti e direzione visiva del brand.", "Versão": "Versione", "inicial": "iniziale", "Atualizado": "Aggiornato", "sugestão pendente": "suggerimento in attesa", "sugestões pendentes": "suggerimenti in attesa", "Tudo alinhado": "Tutto allineato", "da identidade preenchida": "dell'identità completata", "Visão geral": "Panoramica", "Essência": "Essenza", "Público": "Pubblico", "Voz": "Voce", "Conteúdo": "Contenuto", "Visual": "Visuale", "Histórico": "Cronologia",
    "Missão": "Missione", "Visão": "Visione", "Posicionamento": "Posizionamento", "Promessa da marca": "Promessa del brand", "Diferenciais": "Elementi distintivi", "Provas e credenciais": "Prove e credenziali", "Público prioritário": "Pubblico prioritario", "Dores e tensões": "Problemi e tensioni", "Desejos e objetivos": "Desideri e obiettivi", "Tom de voz": "Tono di voce", "Traços de personalidade": "Tratti della personalità", "Exemplos de como falar": "Esempi di come parlare", "Exemplos de como não falar": "Esempi di come non parlare", "Vocabulário preferido": "Vocabolario preferito", "Expressões da marca": "Espressioni del brand", "Termos a evitar": "Termini da evitare", "Direção visual": "Direzione visiva", "Cores da marca": "Colori del brand", "Fonte de destaque": "Font principale", "Fonte de texto": "Font del testo", "Fonte de apoio": "Font di supporto", "Texto de demonstração": "Testo di esempio", "Referências": "Riferimenti", "Um item por linha": "Un elemento per riga",
    "VERIFICAÇÃO DE CONTEÚDO": "VERIFICA DEL CONTENUTO", "Teste uma legenda": "Prova una didascalia", "Cole o texto para conferir se ele conversa com a memória da marca.": "Incolla il testo per verificare se rispetta la memoria del brand.", "Cole aqui a legenda ou o texto que deseja revisar…": "Incolla qui la didascalia o il testo da revisionare…", "Ajustar": "Correggi", "Tudo certo": "Tutto corretto", "Nenhum termo proibido encontrado.": "Nessun termine vietato trovato.", "Vocabulário": "Vocabolario", "Pilar relacionado": "Pilastro collegato", "Nenhuma expressão característica apareceu ainda.": "Non è ancora comparsa alcuna espressione caratteristica.", "Não identificamos conexão clara com um pilar.": "Non è stato individuato un collegamento chiaro con un pilastro.", "Tom esperado": "Tono previsto", "Defina o tom de voz para receber uma orientação mais completa.": "Definisci il tono di voce per ricevere indicazioni più complete.", "A análise acontece enquanto você escreve, sem alterar o conteúdo original.": "L'analisi avviene mentre scrivi, senza modificare il contenuto originale.", "Sugestão enviada para a equipe. Ela ficará pendente até a aprovação.": "Suggerimento inviato al team. Rimarrà in attesa fino all'approvazione.", "Brand Brain atualizado e uma nova versão foi registrada.": "Brand Brain aggiornato e nuova versione registrata.", "Não foi possível salvar.": "Impossibile salvare.", "Não foi possível comentar.": "Impossibile aggiungere il commento."
    , "POSICIONAMENTO": "POSIZIONAMENTO", "Defina o espaço único que a marca deseja ocupar.": "Definisci lo spazio unico che il brand vuole occupare.", "A promessa central da marca aparecerá aqui.": "La promessa centrale del brand apparirà qui.", "VOZ · PERSONALIDADE": "VOCE · PERSONALITÀ", "Defina como a marca fala e se relaciona.": "Definisci come il brand parla e si relaziona.", "Abrir →": "Apri →", "PILARES": "PILASTRI", "pilar": "pilastro", "pilares": "pilastri", "Nenhum pilar definido ainda.": "Nessun pilastro ancora definito.", "VISUAL": "VISUALE", "Paleta": "Palette", "Tipografia": "Tipografia", "Tipografia ainda não definida": "Tipografia non ancora definita", "Explore as seções": "Esplora le sezioni", "Pilares: nome | foco | peso": "Pilastri: nome | focus | peso", "Um pilar por linha. Ex.: Educação | Ensinar com clareza | 40": "Un pilastro per riga. Es.: Educazione | Insegnare con chiarezza | 40", "Use códigos hexadecimais separados por vírgula.": "Usa codici esadecimali separati da virgole.", "PRÉVIA TIPOGRÁFICA": "ANTEPRIMA TIPOGRAFICA", "Defina as fontes acima": "Definisci i font sopra", "Título principal da marca": "Titolo principale del brand", "Detalhe ou assinatura em": "Dettaglio o firma in", "Sua sugestão está em análise": "Il tuo suggerimento è in revisione", "A equipe recebeu a atualização e você verá a nova versão aqui assim que ela for aprovada.": "Il team ha ricevuto l'aggiornamento. La nuova versione apparirà qui dopo l'approvazione.", "Versões publicadas": "Versioni pubblicate", "A primeira versão será criada no próximo salvamento.": "La prima versione sarà creata al prossimo salvataggio.", "Rascunho protegido": "Bozza protetta", "CONVERSA DA MARCA": "CONVERSAZIONE DEL BRAND"
  },
  sv: {
    "Não foi possível atualizar a senha.": "Lösenordet kunde inte uppdateras.", "Não foi possível carregar os arquivados.": "Arkiverat innehåll kunde inte laddas.", "Não foi possível enviar o retorno.": "Din feedback kunde inte skickas.", "Não foi possível enviar a sugestão.": "Förslaget kunde inte skickas.", "Não foi possível salvar a legenda.": "Texten kunde inte sparas.", "Não foi possível criar a etiqueta.": "Taggen kunde inte skapas.", "Não foi possível salvar as etiquetas.": "Taggarna kunde inte sparas.",
    "Organizando a memória da marca…": "Organiserar varumärkesminnet…", "Não foi possível carregar o Brand Brain.": "Brand Brain kunde inte laddas.", "Ainda não publicado": "Inte publicerat ännu", "A fonte de verdade da marca para estratégia, conteúdo e direção visual.": "Den centrala källan för varumärkets strategi, innehåll och visuella riktning.", "Versão": "Version", "inicial": "första", "Atualizado": "Uppdaterad", "sugestão pendente": "väntande förslag", "sugestões pendentes": "väntande förslag", "Tudo alinhado": "Allt är samordnat", "da identidade preenchida": "av identiteten ifylld", "Visão geral": "Översikt", "Essência": "Kärna", "Público": "Målgrupp", "Voz": "Röst", "Conteúdo": "Innehåll", "Visual": "Visuellt", "Histórico": "Historik",
    "Missão": "Uppdrag", "Visão": "Vision", "Posicionamento": "Positionering", "Promessa da marca": "Varumärkeslöfte", "Diferenciais": "Särskiljande faktorer", "Provas e credenciais": "Bevis och meriter", "Público prioritário": "Primär målgrupp", "Dores e tensões": "Problem och spänningar", "Desejos e objetivos": "Önskemål och mål", "Tom de voz": "Tonläge", "Traços de personalidade": "Personlighetsdrag", "Exemplos de como falar": "Exempel på hur vi talar", "Exemplos de como não falar": "Exempel på hur vi inte talar", "Vocabulário preferido": "Föredraget ordförråd", "Expressões da marca": "Varumärkesuttryck", "Termos a evitar": "Ord att undvika", "Direção visual": "Visuell riktning", "Cores da marca": "Varumärkesfärger", "Fonte de destaque": "Rubriktypsnitt", "Fonte de texto": "Brödtexttypsnitt", "Fonte de apoio": "Kompletterande typsnitt", "Texto de demonstração": "Exempeltext", "Referências": "Referenser", "Um item por linha": "En post per rad",
    "VERIFICAÇÃO DE CONTEÚDO": "INNEHÅLLSKONTROLL", "Teste uma legenda": "Testa en text", "Cole o texto para conferir se ele conversa com a memória da marca.": "Klistra in texten för att kontrollera om den stämmer med varumärkesminnet.", "Cole aqui a legenda ou o texto que deseja revisar…": "Klistra in texten du vill granska här…", "Ajustar": "Justera", "Tudo certo": "Allt ser bra ut", "Nenhum termo proibido encontrado.": "Inga förbjudna ord hittades.", "Vocabulário": "Ordförråd", "Pilar relacionado": "Relaterad pelare", "Nenhuma expressão característica apareceu ainda.": "Inget karakteristiskt uttryck har dykt upp ännu.", "Não identificamos conexão clara com um pilar.": "Ingen tydlig koppling till en pelare hittades.", "Tom esperado": "Förväntat tonläge", "Defina o tom de voz para receber uma orientação mais completa.": "Definiera tonläget för att få mer fullständig vägledning.", "A análise acontece enquanto você escreve, sem alterar o conteúdo original.": "Analysen sker medan du skriver utan att ändra originalinnehållet.", "Sugestão enviada para a equipe. Ela ficará pendente até a aprovação.": "Förslaget har skickats till teamet och väntar på godkännande.", "Brand Brain atualizado e uma nova versão foi registrada.": "Brand Brain har uppdaterats och en ny version registrerats.", "Não foi possível salvar.": "Det gick inte att spara.", "Não foi possível comentar.": "Kommentaren kunde inte läggas till."
    , "POSICIONAMENTO": "POSITIONERING", "Defina o espaço único que a marca deseja ocupar.": "Definiera den unika plats som varumärket ska ta.", "A promessa central da marca aparecerá aqui.": "Varumärkets centrala löfte visas här.", "VOZ · PERSONALIDADE": "RÖST · PERSONLIGHET", "Defina como a marca fala e se relaciona.": "Definiera hur varumärket talar och skapar relationer.", "Abrir →": "Öppna →", "PILARES": "PELARE", "pilar": "pelare", "pilares": "pelare", "Nenhum pilar definido ainda.": "Inga pelare har definierats ännu.", "VISUAL": "VISUELLT", "Paleta": "Palett", "Tipografia": "Typografi", "Tipografia ainda não definida": "Typografi har inte definierats ännu", "Explore as seções": "Utforska avsnitten", "Pilares: nome | foco | peso": "Pelare: namn | fokus | vikt", "Um pilar por linha. Ex.: Educação | Ensinar com clareza | 40": "En pelare per rad. T.ex.: Utbildning | Undervisa tydligt | 40", "Use códigos hexadecimais separados por vírgula.": "Använd kommaseparerade hexadecimala koder.", "PRÉVIA TIPOGRÁFICA": "FÖRHANDSVISNING AV TYPOGRAFI", "Defina as fontes acima": "Ange typsnitten ovan", "Título principal da marca": "Varumärkets huvudrubrik", "Detalhe ou assinatura em": "Detalj eller signatur i", "Sua sugestão está em análise": "Ditt förslag granskas", "A equipe recebeu a atualização e você verá a nova versão aqui assim que ela for aprovada.": "Teamet har fått uppdateringen. Den nya versionen visas här när den har godkänts.", "Versões publicadas": "Publicerade versioner", "A primeira versão será criada no próximo salvamento.": "Den första versionen skapas nästa gång du sparar.", "Rascunho protegido": "Utkast skyddat", "CONVERSA DA MARCA": "VARUMÄRKESSAMTAL"
  }
};

export function normalizePortalLocale(value?: string | null): PortalLocale {
  const locale = (value ?? "pt").trim().toLocaleLowerCase();
  if (locale.startsWith("en") || locale.includes("ingl")) return "en";
  if (locale.startsWith("es") || locale.includes("espa")) return "es";
  if (locale.startsWith("it") || locale.includes("ital")) return "it";
  if (locale.startsWith("sv") || locale.includes("suec") || locale.includes("swed")) return "sv";
  return "pt";
}

export function portalLocaleTag(value?: string | null) {
  return ({ pt: "pt-BR", en: "en-US", es: "es-ES", it: "it-IT", sv: "sv-SE" } as const)[normalizePortalLocale(value)];
}

export function portalText(locale: string | null | undefined, source: string) {
  const normalized = normalizePortalLocale(locale);
  return normalized === "pt" ? source : translations[normalized][source] ?? brandBrainTranslations[normalized][source] ?? source;
}
