import { useEffect, useState } from "react";
import {
  createAdminReport, deleteAdminReport, extractAdminReportMetrics, listAdminClients, listAdminReports,
  listPortalReportsBySlug, loadClientMetaAdsInsights, loadClientMetaAssets, loadClientMetaInsights, loadMetaStatus,
  publishAdminReport, updateAdminReport, uploadAdminMedia,
  ApiRequestTimeoutError,
  type AdminClientOption, type ClientMetaAdsInsights, type ClientMetaAssets, type ClientMetaInsights, type ClientReport,
  type MetaStatus, type ReportMetricKey, type ReportMetrics,
} from "./api";

const METRICS: Array<[ReportMetricKey, string]> = [["reach", "Alcance"], ["impressions", "Visualizações"], ["engagement", "Interações"], ["followers", "Seguidores"], ["visits", "Visitas ao perfil"], ["clicks", "Cliques no link"]];
const FACEBOOK_EXTRAS = [["posts", "Publicações em destaque"], ["reactions", "Reações nos destaques"], ["comments", "Comentários nos destaques"], ["shares", "Compartilhamentos nos destaques"]] as const;
const CHECKLIST = ["Visão geral", "Melhores conteúdos"];
const emptyChannel = () => ({ reach: null, impressions: null, engagement: null, followers: null, visits: null, clicks: null });
const emptyMetrics = (): ReportMetrics => ({ instagram: emptyChannel(), facebook: { ...emptyChannel(), posts: null, reactions: null, comments: null, shares: null } });
const fallbackClients: AdminClientOption[] = [{ id: "demo-aplikasi", name: "Aplikasi", slug: "aplikasi" }, { id: "demo-minas-home", name: "Minas Home ADS", slug: "minas-home-ads" }, { id: "demo-podcast", name: "Podcast Líder de Elite", slug: "podcast-lider-de-elite" }];
const dateValue = (date: Date) => date.toISOString().slice(0, 10);
const defaultReportTitle = (periodEnd: Date) => `Relatório de postagens ${new Intl.DateTimeFormat("pt-BR", { month: "long" }).format(periodEnd).toLocaleUpperCase("pt-BR")} ${periodEnd.getFullYear()}`;
type ReportLocale = "pt" | "en" | "es" | "it" | "sv";
const reportLocale = (locale?: string): ReportLocale => ["en", "es", "it", "sv"].includes(locale ?? "") ? locale as ReportLocale : "pt";
const browserLocale: Record<ReportLocale, string> = { pt: "pt-BR", en: "en-US", es: "es-ES", it: "it-IT", sv: "sv-SE" };
const reportDateValue = (value: unknown) => { const raw = String(value ?? ""); const datePart = raw.match(/^\d{4}-\d{2}-\d{2}/)?.[0] ?? ""; if (datePart) return datePart; const parsed = new Date(raw); return Number.isNaN(parsed.getTime()) ? "" : parsed.toISOString().slice(0, 10); };
const formatReportDate = (value: unknown, locale: ReportLocale = "pt") => { const datePart = reportDateValue(value); return datePart ? new Date(`${datePart}T12:00:00`).toLocaleDateString(browserLocale[locale]) : "—"; };

const reportText = {
  pt: { performance: "RELATÓRIO DE PERFORMANCE", published: "Publicado", draft: "Rascunho", summary: "Resumo geral", organic: "PERFORMANCE ORGÂNICA", highlights: "CONTEÚDOS EM DESTAQUE", teamNotes: "Notas da equipe", results: "RESULTADOS", reports: "Relatórios", portalIntro: "Acompanhe a performance das suas redes e baixe cada período em PDF.", download: "Baixar PDF", empty: "Nenhum relatório publicado ainda.", generated: "Relatório gerado pela DesignHub", unavailable: "Não disponível", noMetrics: "Nenhuma métrica foi preenchida neste relatório.", bestContent: "Conteúdo em destaque" },
  en: { performance: "PERFORMANCE REPORT", published: "Published", draft: "Draft", summary: "Overview", organic: "ORGANIC PERFORMANCE", highlights: "HIGHLIGHTED CONTENT", teamNotes: "Team notes", results: "RESULTS", reports: "Reports", portalIntro: "Track your social media performance and download each period as a PDF.", download: "Download PDF", empty: "No reports have been published yet.", generated: "Report generated by DesignHub", unavailable: "Not available", noMetrics: "No metrics have been added to this report.", bestContent: "Highlighted content" },
  es: { performance: "INFORME DE RENDIMIENTO", published: "Publicado", draft: "Borrador", summary: "Resumen general", organic: "RENDIMIENTO ORGÁNICO", highlights: "CONTENIDO DESTACADO", teamNotes: "Notas del equipo", results: "RESULTADOS", reports: "Informes", portalIntro: "Sigue el rendimiento de tus redes y descarga cada período en PDF.", download: "Descargar PDF", empty: "Aún no hay informes publicados.", generated: "Informe generado por DesignHub", unavailable: "No disponible", noMetrics: "No se añadieron métricas a este informe.", bestContent: "Contenido destacado" },
  it: { performance: "REPORT DELLE PERFORMANCE", published: "Pubblicato", draft: "Bozza", summary: "Riepilogo generale", organic: "PERFORMANCE ORGANICA", highlights: "CONTENUTI IN EVIDENZA", teamNotes: "Note del team", results: "RISULTATI", reports: "Report", portalIntro: "Segui le performance dei tuoi social e scarica ogni periodo in PDF.", download: "Scarica PDF", empty: "Nessun report pubblicato.", generated: "Report generato da DesignHub", unavailable: "Non disponibile", noMetrics: "Nessuna metrica è stata aggiunta al report.", bestContent: "Contenuto in evidenza" },
  sv: { performance: "PRESTANDARAPPORT", published: "Publicerad", draft: "Utkast", summary: "Sammanfattning", organic: "ORGANISK PRESTANDA", highlights: "UTVALT INNEHÅLL", teamNotes: "Teamets anteckningar", results: "RESULTAT", reports: "Rapporter", portalIntro: "Följ resultatet för dina sociala medier och ladda ner varje period som PDF.", download: "Ladda ner PDF", empty: "Inga rapporter har publicerats ännu.", generated: "Rapport genererad av DesignHub", unavailable: "Inte tillgängligt", noMetrics: "Inga mätvärden har lagts till i rapporten.", bestContent: "Utvalt innehåll" },
} as const;
const metricText: Record<ReportLocale, Record<string, string>> = {
  pt: { reach: "Alcance", impressions: "Visualizações", engagement: "Interações", followers: "Seguidores", visits: "Visitas ao perfil", clicks: "Cliques no link", posts: "Publicações em destaque", reactions: "Reações nos destaques", comments: "Comentários nos destaques", shares: "Compartilhamentos nos destaques" },
  en: { reach: "Reach", impressions: "Views", engagement: "Interactions", followers: "Followers", visits: "Profile visits", clicks: "Link clicks", posts: "Highlighted posts", reactions: "Reactions on highlights", comments: "Comments on highlights", shares: "Shares on highlights" },
  es: { reach: "Alcance", impressions: "Visualizaciones", engagement: "Interacciones", followers: "Seguidores", visits: "Visitas al perfil", clicks: "Clics en enlaces", posts: "Publicaciones destacadas", reactions: "Reacciones destacadas", comments: "Comentarios destacados", shares: "Compartidos destacados" },
  it: { reach: "Copertura", impressions: "Visualizzazioni", engagement: "Interazioni", followers: "Follower", visits: "Visite al profilo", clicks: "Clic sul link", posts: "Post in evidenza", reactions: "Reazioni in evidenza", comments: "Commenti in evidenza", shares: "Condivisioni in evidenza" },
  sv: { reach: "Räckvidd", impressions: "Visningar", engagement: "Interaktioner", followers: "Följare", visits: "Profilbesök", clicks: "Länkklick", posts: "Utvalda inlägg", reactions: "Reaktioner på utvalda", comments: "Kommentarer på utvalda", shares: "Delningar av utvalda" },
};
const number = (value: number, locale: ReportLocale = "pt") => new Intl.NumberFormat(browserLocale[locale], { notation: value >= 10_000 ? "compact" : "standard", maximumFractionDigits: 1 }).format(value);
const displayMetric = (value: number | null | undefined, locale: ReportLocale) => value == null ? reportText[locale].unavailable : number(value, locale);
const currency = (value: number | null | undefined, code: string | null | undefined, locale: ReportLocale) => value == null ? reportText[locale].unavailable : new Intl.NumberFormat(browserLocale[locale], { style: "currency", currency: code || "BRL", maximumFractionDigits: 2 }).format(value);
const percent = (value: number | null | undefined, locale: ReportLocale) => value == null ? reportText[locale].unavailable : `${new Intl.NumberFormat(browserLocale[locale], { maximumFractionDigits: 2 }).format(value)}%`;
const decimal = (value: number | null | undefined, locale: ReportLocale) => value == null ? reportText[locale].unavailable : new Intl.NumberFormat(browserLocale[locale], { maximumFractionDigits: 2 }).format(value);
const localReportKey = (clientId: string) => `designhub-v2-local-reports:${clientId}`;
const readLocalReports = (clientId: string): ClientReport[] => { try { return JSON.parse(window.localStorage.getItem(localReportKey(clientId)) ?? "[]") as ClientReport[]; } catch { return []; } };
const writeLocalReports = (clientId: string, reports: ClientReport[]) => window.localStorage.setItem(localReportKey(clientId), JSON.stringify(reports));

function reportSummary(report: Pick<ClientReport, "metrics" | "highlights">, locale: ReportLocale = "pt") {
  const statements: string[] = [];
  const { instagram, facebook } = report.metrics;
  const instagramAvailable = [["reach", instagram.reach], ["engagement", instagram.engagement]] as const;
  const facebookAvailable = [["reach", facebook.reach], ["followers", facebook.followers], ["engagement", facebook.engagement]] as const;
  const describe = (channel: string, values: ReadonlyArray<readonly [string, number | null]>) => {
    const parts = values.filter((entry): entry is readonly [string, number] => entry[1] != null).map(([key, value]) => `${number(value, locale)} ${metricText[locale][key].toLocaleLowerCase(browserLocale[locale])}`);
    if (parts.length) statements.push(`${channel}: ${parts.join(" · ")}`);
  };
  describe("Instagram", instagramAvailable);
  describe("Facebook", facebookAvailable);
  const best = [...report.highlights].sort((a, b) => b.value - a.value)[0];
  if (best) statements.push(`${reportText[locale].bestContent}: “${best.title}”`);
  return statements.length ? `${statements.join(". ")}.` : reportText[locale].noMetrics;
}

function visibleReportNotes(value: string | null) {
  const raw = value?.trim() ?? "";
  if (!raw.startsWith("Observações:\n{")) return raw;
  const jsonStart = raw.indexOf("{"); const jsonEnd = raw.indexOf("\n\n", jsonStart);
  try { const parsed = JSON.parse(raw.slice(jsonStart, jsonEnd < 0 ? undefined : jsonEnd)) as { text?: unknown }; const observation = typeof parsed.text === "string" ? parsed.text.trim() : ""; const remainder = jsonEnd < 0 ? "" : raw.slice(jsonEnd + 2).trim(); return [observation ? `Observações:\n${observation}` : "", remainder].filter(Boolean).join("\n\n"); } catch { return raw; }
}

function reportPlatformRows(report: Pick<ClientReport, "metrics">, channel: "instagram" | "facebook") {
  if (channel === "instagram") return METRICS.map(([key]) => [key, report.metrics.instagram[key]] as const);
  return [...METRICS.map(([key]) => [key, report.metrics.facebook[key]] as const), ...FACEBOOK_EXTRAS.map(([key]) => [key, report.metrics.facebook[key]] as const)];
}

function PlatformMetrics({ report, channel, locale }: { report: ClientReport; channel: "instagram" | "facebook"; locale: ReportLocale }) {
  return <article className={`report-platform ${channel}`}><header><span aria-hidden="true">{channel === "instagram" ? "◎" : "f"}</span><h3>{channel === "instagram" ? "Instagram" : "Facebook"}</h3></header><div>{reportPlatformRows(report, channel).map(([key, value]) => <p className={value == null ? "unavailable" : ""} key={key}><span>{metricText[locale][key]}</span><b>{displayMetric(value, locale)}</b></p>)}</div></article>;
}

function AdsMetricsSection({ report, locale }: { report: ClientReport; locale: ReportLocale }) {
  const ads = report.metrics.ads;
  if (!ads) return null;
  const rows = [
    ["Investimento", currency(ads.spend, ads.currency, locale)],
    ["Alcance pago", displayMetric(ads.reach, locale)],
    ["Impressões", displayMetric(ads.impressions, locale)],
    ["Cliques no link", displayMetric(ads.inlineLinkClicks ?? ads.clicks, locale)],
    ["CTR", percent(ads.ctr, locale)],
    ["CPC", currency(ads.cpc, ads.currency, locale)],
    ["CPM", currency(ads.cpm, ads.currency, locale)],
    ["Frequência", decimal(ads.frequency, locale)],
  ] as const;
  return <section className="report-ads"><div className="report-ads-heading"><span>META ADS</span><div><h3>Performance de anúncios</h3><p>{ads.accountName || "Conta de anúncios"}{ads.currency ? ` · ${ads.currency}` : ""}</p></div></div><div className="report-ads-kpis">{rows.map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>{ads.campaigns.length ? <div className="report-ads-campaigns"><h4>Campanhas com maior investimento</h4>{ads.campaigns.slice(0, 4).map((campaign) => <div key={campaign.campaignId || campaign.campaignName}><div><strong>{campaign.campaignName || "Campanha"}</strong><small>{campaign.objective?.replace(/^OUTCOME_/, "").replace(/_/g, " ") || "Meta Ads"}</small></div><span>{currency(campaign.spend, ads.currency, locale)}</span><span>{displayMetric(campaign.reach, locale)} alcance</span><span>{percent(campaign.ctr, locale)} CTR</span></div>)}</div> : null}</section>;
}

function HighlightThumbnail({ item }: { item: ClientReport["highlights"][number] }) {
  const platform = item.channel === "instagram" ? "Instagram" : "Facebook";
  return <div className={`report-highlight-thumbnail ${item.channel}`}><span aria-hidden="true">{item.channel === "instagram" ? "◎" : "f"}</span>{item.thumbnailUrl ? <img src={item.thumbnailUrl} alt={`Publicação do ${platform}`} loading="lazy" onError={(event) => { event.currentTarget.hidden = true; }} /> : null}</div>;
}

function ReportDocument({ report, clientName, locale = "pt", printable = false }: { report: ClientReport; clientName: string; locale?: string; printable?: boolean }) {
  const language = reportLocale(locale); const copy = reportText[language]; const notes = visibleReportNotes(report.notes);
  return <article className={printable ? "report-document printable-report" : "report-document"}>
    <header><div><span>{copy.performance}</span><h2>{clientName}</h2><p>{formatReportDate(report.periodStart, language)} a {formatReportDate(report.periodEnd, language)}</p></div><b>{report.status === "published" ? copy.published : copy.draft}</b></header>
    <section className="report-summary"><strong>{copy.summary}</strong><p>{reportSummary(report, language)}</p></section>
    <section className="report-organic"><span>{copy.organic}</span><div className="report-platform-grid"><PlatformMetrics report={report} channel="instagram" locale={language} /><PlatformMetrics report={report} channel="facebook" locale={language} /></div></section>
    {report.metrics.ads ? <AdsMetricsSection report={report} locale={language} /> : null}
    {report.highlights.length ? <section className="report-highlights"><span>{copy.highlights}</span><div className="report-highlight-grid">{report.highlights.map((item, index) => <article className="report-highlight-card" key={`${item.channel}-${item.title}-${index}`}><HighlightThumbnail item={item} /><div><p>{item.title}</p><footer><span>{item.channel === "instagram" ? "Instagram" : "Facebook"}</span><strong>{number(item.value, language)} {metricText[language].engagement.toLocaleLowerCase(browserLocale[language])}</strong></footer></div></article>)}</div></section> : null}
    {notes ? <section className="report-notes"><strong>{copy.teamNotes}</strong><p>{notes}</p></section> : null}
  </article>;
}

async function thumbnailDataUrl(url: string | null | undefined) {
  if (!url) return null;
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), 5_000);
  try {
    const response = await fetch(url, { signal: controller.signal, cache: "force-cache" });
    if (!response.ok) return null;
    const blob = await response.blob();
    if (!blob.type.startsWith("image/") || blob.size > 10_000_000) return null;
    const bitmap = await createImageBitmap(blob);
    const canvas = document.createElement("canvas");
    canvas.width = 480; canvas.height = 360;
    const context = canvas.getContext("2d");
    if (!context) { bitmap.close(); return null; }
    context.fillStyle = "#f8faff"; context.fillRect(0, 0, canvas.width, canvas.height);
    context.beginPath(); context.roundRect(0, 0, canvas.width, canvas.height, 28); context.clip();
    const scale = Math.max(canvas.width / bitmap.width, canvas.height / bitmap.height);
    const width = bitmap.width * scale; const height = bitmap.height * scale;
    context.drawImage(bitmap, (canvas.width - width) / 2, (canvas.height - height) / 2, width, height);
    bitmap.close();
    return canvas.toDataURL("image/jpeg", 0.82);
  } catch { return null; }
  finally { window.clearTimeout(timeout); }
}

async function downloadReportPdf(report: ClientReport, clientName: string, locale = "pt") {
  const { jsPDF } = await import("jspdf");
  const language = reportLocale(locale); const copy = reportText[language];
  const pdf = new jsPDF({ unit: "pt", format: "a4" }); const contentX = 42;
  const pdfHighlights = report.highlights.map((item, index) => ({ item, index })).sort((a, b) => b.item.value - a.item.value || a.index - b.index).slice(0, 4).map(({ item }) => item);
  const thumbnails = await Promise.all(pdfHighlights.map((item) => thumbnailDataUrl(item.thumbnailUrl)));
  const drawBackground = () => { pdf.setFillColor(29, 39, 73); pdf.rect(0, 0, 595, 842, "F"); pdf.setFillColor(73, 88, 207); pdf.circle(535, 58, 112, "F"); pdf.setFillColor(53, 190, 220); pdf.circle(502, 28, 74, "F"); };
  const drawFooter = () => { pdf.setTextColor(255, 255, 255); pdf.setFontSize(9); pdf.text(copy.generated, contentX, 820); };
  const clampLines = (text: string, maxWidth: number, maxLines: number) => {
    const lines = pdf.splitTextToSize(text.replace(/\s+/g, " ").trim(), maxWidth) as string[];
    if (lines.length <= maxLines) return lines;
    const visible = lines.slice(0, maxLines); let last = visible[maxLines - 1].replace(/[.,;:!?\s]+$/, "");
    while (last.length && pdf.getTextWidth(`${last}…`) > maxWidth) last = last.slice(0, -1).trimEnd();
    visible[maxLines - 1] = `${last}…`; return visible;
  };

  drawBackground();
  pdf.setTextColor(255, 255, 255); pdf.setFontSize(10); pdf.text(copy.performance, contentX, 48); pdf.setFontSize(27); pdf.text(clientName, contentX, 79); pdf.setFontSize(11); pdf.text(`${formatReportDate(report.periodStart, language)} a ${formatReportDate(report.periodEnd, language)}`, contentX, 100);
  pdf.setFillColor(255, 255, 255); pdf.roundedRect(25, 128, 545, 668, 22, 22, "F"); pdf.setTextColor(39, 51, 87); pdf.setFontSize(18); pdf.text(report.title, contentX, 164, { maxWidth: 490 }); pdf.setTextColor(92, 106, 137); pdf.setFontSize(10); pdf.text(reportSummary(report, language), contentX, 190, { maxWidth: 480, lineHeightFactor: 1.4 });
  pdf.setTextColor(79, 91, 122); pdf.setFontSize(9); pdf.text(copy.organic, contentX, 235);
  (["instagram", "facebook"] as const).forEach((channel, channelIndex) => { const x = contentX + channelIndex * 258; pdf.setFillColor(channel === "instagram" ? 252 : 242, channel === "instagram" ? 243 : 247, 255); pdf.roundedRect(x, 252, 246, 300, 14, 14, "F"); pdf.setTextColor(39, 51, 87); pdf.setFontSize(16); pdf.text(channel === "instagram" ? "Instagram" : "Facebook", x + 15, 281); reportPlatformRows(report, channel).forEach(([key, value], rowIndex) => { const y = 312 + rowIndex * 25; if (y > 535) return; pdf.setTextColor(103, 117, 148); pdf.setFontSize(8); pdf.text(metricText[language][key], x + 15, y, { maxWidth: 145 }); pdf.setTextColor(value == null ? 145 : 39, value == null ? 151 : 51, value == null ? 166 : 87); pdf.setFontSize(value == null ? 8 : 11); pdf.text(displayMetric(value, language), x + 230, y, { align: "right" }); }); });
  const notes = visibleReportNotes(report.notes); if (notes) { pdf.setTextColor(79, 91, 122); pdf.setFontSize(9); pdf.text(copy.teamNotes.toUpperCase(), contentX, 735); pdf.setTextColor(82, 94, 122); pdf.text(notes, contentX, 754, { maxWidth: 500 }); }
  drawFooter();

  if (report.metrics.ads) {
    const ads = report.metrics.ads;
    pdf.addPage(); drawBackground();
    pdf.setTextColor(255, 255, 255); pdf.setFontSize(9); pdf.text(copy.performance, contentX, 40); pdf.setFontSize(22); pdf.text("META ADS", contentX, 70); pdf.setFontSize(10); pdf.text(`${clientName} · ${formatReportDate(report.periodStart, language)} a ${formatReportDate(report.periodEnd, language)}`, contentX, 91);
    pdf.setFillColor(255, 255, 255); pdf.roundedRect(25, 112, 545, 684, 22, 22, "F");
    pdf.setTextColor(39, 51, 87); pdf.setFontSize(17); pdf.text("Performance de anúncios", contentX, 150);
    pdf.setTextColor(103, 117, 148); pdf.setFontSize(9); pdf.text(`${ads.accountName || "Conta de anúncios"}${ads.currency ? ` · ${ads.currency}` : ""}`, contentX, 169);
    const adCards = [
      ["Investimento", currency(ads.spend, ads.currency, language)],
      ["Alcance pago", displayMetric(ads.reach, language)],
      ["Impressões", displayMetric(ads.impressions, language)],
      ["Cliques no link", displayMetric(ads.inlineLinkClicks ?? ads.clicks, language)],
      ["CTR", percent(ads.ctr, language)],
      ["CPC", currency(ads.cpc, ads.currency, language)],
      ["CPM", currency(ads.cpm, ads.currency, language)],
      ["Frequência", decimal(ads.frequency, language)],
    ] as const;
    adCards.forEach(([label, value], index) => {
      const x = contentX + (index % 2) * 258; const y = 196 + Math.floor(index / 2) * 70;
      pdf.setFillColor(index % 2 ? 243 : 247, index % 2 ? 245 : 249, 255); pdf.roundedRect(x, y, 246, 55, 11, 11, "F");
      pdf.setTextColor(103, 117, 148); pdf.setFontSize(8); pdf.text(label.toUpperCase(), x + 13, y + 18);
      pdf.setTextColor(39, 51, 87); pdf.setFontSize(15); pdf.text(value, x + 13, y + 41);
    });
    if (ads.campaigns.length) {
      pdf.setTextColor(79, 91, 122); pdf.setFontSize(9); pdf.text("CAMPANHAS COM MAIOR INVESTIMENTO", contentX, 505);
      ads.campaigns.slice(0, 4).forEach((campaign, index) => {
        const y = 535 + index * 52;
        pdf.setFillColor(248, 250, 255); pdf.roundedRect(contentX, y - 18, 511, 42, 9, 9, "F");
        pdf.setTextColor(39, 51, 87); pdf.setFontSize(9.5); pdf.text(clampLines(campaign.campaignName || "Campanha", 285, 1), contentX + 12, y);
        pdf.setTextColor(103, 117, 148); pdf.setFontSize(8); pdf.text(`${currency(campaign.spend, ads.currency, language)} · ${displayMetric(campaign.reach, language)} alcance · ${percent(campaign.ctr, language)} CTR`, contentX + 12, y + 15);
      });
    }
    drawFooter();
  }

  if (pdfHighlights.length) {
    pdf.addPage(); drawBackground();
    pdf.setTextColor(255, 255, 255); pdf.setFontSize(9); pdf.text(copy.performance, contentX, 40); pdf.setFontSize(22); pdf.text(copy.highlights, contentX, 70); pdf.setFontSize(10); pdf.text(`${clientName} · ${formatReportDate(report.periodStart, language)} a ${formatReportDate(report.periodEnd, language)}`, contentX, 91);
    pdf.setFillColor(255, 255, 255); pdf.roundedRect(25, 112, 545, 684, 22, 22, "F");
    pdfHighlights.forEach((item, index) => {
      const x = 42; const y = 132 + index * 154; const width = 511; const height = 138; const imageX = x + 11; const imageY = y + 11; const imageWidth = 158; const imageHeight = 116; const textX = imageX + imageWidth + 17; const textWidth = x + width - 14 - textX;
      pdf.setFillColor(248, 250, 255); pdf.roundedRect(x, y, width, height, 14, 14, "F");
      if (thumbnails[index]) pdf.addImage(thumbnails[index]!, "JPEG", imageX, imageY, imageWidth, imageHeight, undefined, "FAST");
      else { const facebook = item.channel === "facebook"; pdf.setFillColor(facebook ? 53 : 123, facebook ? 112 : 74, facebook ? 224 : 201); pdf.roundedRect(imageX, imageY, imageWidth, imageHeight, 10, 10, "F"); pdf.setFillColor(255, 255, 255); pdf.circle(imageX + imageWidth / 2, imageY + 47, 20, "F"); pdf.setTextColor(facebook ? 53 : 123, facebook ? 112 : 74, facebook ? 224 : 201); pdf.setFontSize(18); pdf.text(facebook ? "f" : "◎", imageX + imageWidth / 2, imageY + 53, { align: "center" }); pdf.setTextColor(255, 255, 255); pdf.setFontSize(8); pdf.text(facebook ? "Facebook" : "Instagram", imageX + imageWidth / 2, imageY + 86, { align: "center" }); }
      pdf.setTextColor(item.channel === "facebook" ? 49 : 167, item.channel === "facebook" ? 103 : 65, item.channel === "facebook" ? 209 : 139); pdf.setFont("helvetica", "bold"); pdf.setFontSize(8); pdf.text(item.channel === "facebook" ? "FACEBOOK" : "INSTAGRAM", textX, y + 24);
      pdf.setTextColor(38, 49, 82); pdf.setFontSize(9.5); pdf.text(clampLines(item.title, textWidth, 3), textX, y + 49, { lineHeightFactor: 1.35 });
      if (Number.isFinite(item.value) && item.value > 0) { pdf.setTextColor(42, 54, 88); pdf.setFontSize(10); pdf.text(`${number(item.value, language)} ${metricText[language].engagement.toLocaleLowerCase(browserLocale[language])}`, x + width - 14, y + height - 16, { align: "right" }); }
      pdf.setFont("helvetica", "normal");
    });
    drawFooter();
  }
  pdf.save(`${report.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`);
}

function sumKnown(values: Array<number | null | undefined>, emptyValue: number | null) { const known = values.filter((value): value is number => typeof value === "number"); return known.length ? known.reduce((sum, value) => sum + value, 0) : emptyValue; }
function metaHighlights(insights: ClientMetaInsights): ClientReport["highlights"] {
  const candidates: Array<ClientReport["highlights"][number] & { identity: string }> = [];
  for (const item of insights.instagram?.topContent ?? []) candidates.push({ identity: `instagram:${item.id}`, channel: "instagram", title: item.caption?.trim() || "Publicação do Instagram", value: item.totalInteractions ?? sumKnown([item.likes, item.comments, item.shares], 0) ?? 0, thumbnailUrl: item.thumbnailUrl, permalink: item.permalink, metricLabel: "interactions" });
  for (const item of insights.facebook?.topContent ?? []) candidates.push({ identity: `facebook:${item.id}`, channel: "facebook", title: item.message?.trim() || "Publicação do Facebook", value: item.interactions ?? sumKnown([item.reactions, item.comments, item.shares], 0) ?? 0, thumbnailUrl: item.thumbnailUrl, permalink: item.permalink, metricLabel: "interactions" });
  const seen = new Set<string>(); return candidates.sort((a, b) => b.value - a.value).filter((item) => !seen.has(item.identity) && Boolean(seen.add(item.identity))).slice(0, 8).map(({ identity: _identity, ...item }) => ({ ...item, title: item.title.slice(0, 255) }));
}
function metricsFromMeta(insights: ClientMetaInsights, current: ReportMetrics) {
  const metrics: ReportMetrics = { instagram: { ...current.instagram }, facebook: { ...current.facebook }, ads: current.ads ?? null }; const imported: string[] = [];
  if (insights.instagram && insights.sources.instagram !== "failed") { const values = insights.instagram.metrics; metrics.instagram = { reach: values.reach, impressions: values.views, engagement: values.interactions, followers: values.followers, visits: values.profileViews, clicks: values.linkClicks }; for (const [key] of METRICS) if (metrics.instagram[key] != null) imported.push(`instagram.${key}`); }
  if (insights.facebook && insights.sources.facebook !== "failed") { const values = insights.facebook.metrics; const postListFailed = insights.warnings.some((warning) => warning.metricOrOperation === "facebook.posts.list"); const emptyAggregate = postListFailed ? null : 0; metrics.facebook = { reach: values.reach, impressions: values.views ?? values.impressions, engagement: values.engagement, followers: values.followers ?? values.fans, visits: values.pageViews, clicks: null, posts: postListFailed ? null : insights.facebook.topContent.length, reactions: sumKnown(insights.facebook.topContent.map((item) => item.reactions), emptyAggregate), comments: sumKnown(insights.facebook.topContent.map((item) => item.comments), emptyAggregate), shares: sumKnown(insights.facebook.topContent.map((item) => item.shares), emptyAggregate) }; for (const [key, value] of reportPlatformRows({ metrics }, "facebook")) if (value != null) imported.push(`facebook.${key}`); }
  return { metrics, imported };
}

function adsFromMeta(insights: ClientMetaAdsInsights): NonNullable<ReportMetrics["ads"]> {
  return {
    accountName: insights.adAccount.name,
    currency: insights.adAccount.currency,
    ...insights.summary,
    campaigns: insights.campaigns.map((campaign) => ({
      campaignId: campaign.campaignId,
      campaignName: campaign.campaignName,
      objective: campaign.objective,
      spend: campaign.spend,
      reach: campaign.reach,
      impressions: campaign.impressions,
      clicks: campaign.clicks,
      inlineLinkClicks: campaign.inlineLinkClicks,
      ctr: campaign.ctr,
      cpc: campaign.cpc,
      cpm: campaign.cpm,
    })),
  };
}

export function ReportsWorkspace({ newReportSignal = 0 }: { newReportSignal?: number }) {
  const [clients, setClients] = useState<AdminClientOption[]>([]); const [clientId, setClientId] = useState(""); const [reports, setReports] = useState<ClientReport[]>([]); const [editing, setEditing] = useState<ClientReport | null>(null); const [files, setFiles] = useState<Record<string, File>>({}); const [reading, setReading] = useState(false); const [importingMeta, setImportingMeta] = useState(false); const [message, setMessage] = useState(""); const [messageTone, setMessageTone] = useState<"success" | "warning" | "error" | "timeout">("success"); const [localMode, setLocalMode] = useState(false); const [importedFields, setImportedFields] = useState<string[]>([]); const [metaStatus, setMetaStatus] = useState<MetaStatus | null>(null); const [metaAssets, setMetaAssets] = useState<ClientMetaAssets | null>(null);
  const selectedClient = clients.find((client) => client.id === clientId);
  const refresh = async (id = clientId) => { if (!id) return; try { const response = await listAdminReports(id); setReports(response.items); setLocalMode(false); } catch { setLocalMode(true); setReports(readLocalReports(id)); } };
  const refreshMetaContext = async (id: string) => { try { const [status, assets] = await Promise.all([loadMetaStatus(), loadClientMetaAssets(id)]); setMetaStatus(status); setMetaAssets(assets.assets); } catch { setMetaStatus(null); setMetaAssets(null); } };
  useEffect(() => { void listAdminClients().then((result) => { if (result.items.length) { setClients(result.items); setClientId(result.items[0].id); } }).catch(() => { setClients(fallbackClients); setClientId(fallbackClients[0].id); setLocalMode(true); }); }, []);
  useEffect(() => { if (!clientId) return; setEditing((current) => current?.clientAccountId === clientId ? current : null); setFiles({}); setMessage(""); setImportedFields([]); if (clientId.startsWith("demo-")) { setReports(readLocalReports(clientId)); setMetaStatus(null); setMetaAssets(null); return; } void refresh(clientId); void refreshMetaContext(clientId); }, [clientId]);
  const newReport = () => { if (!clientId) return; const end = new Date(); const start = new Date(); start.setDate(end.getDate() - 30); setFiles({}); setImportedFields([]); setEditing({ id: "", clientAccountId: clientId, title: defaultReportTitle(end), periodStart: dateValue(start), periodEnd: dateValue(end), status: "draft", metrics: emptyMetrics(), highlights: [], evidenceUrls: [], notes: null, publishedAt: null, createdAt: "", updatedAt: "" }); };
  useEffect(() => { if (newReportSignal > 0 && clientId) newReport(); }, [newReportSignal, clientId]);
  const importMeta = async () => {
    if (!editing) return;
    setImportingMeta(true); setMessage("");
    const since = reportDateValue(editing.periodStart); const until = reportDateValue(editing.periodEnd);
    const hasOrganic = Boolean(metaAssets?.instagramAccountId || metaAssets?.facebookPageId);
    const hasAds = Boolean(metaAssets?.metaAdAccountId);
    try {
      const [organicResult, adsResult] = await Promise.allSettled([
        hasOrganic ? loadClientMetaInsights(clientId, since, until) : Promise.resolve(null),
        hasAds ? loadClientMetaAdsInsights(clientId, since, until) : Promise.resolve(null),
      ]);
      let nextMetrics: ReportMetrics = editing.metrics;
      let nextHighlights = editing.highlights;
      let imported: string[] = [];
      let successes = 0;
      const warnings: string[] = [];

      if (organicResult.status === "fulfilled" && organicResult.value) {
        const insights = organicResult.value;
        if (insights.status !== "failed") {
          const mapped = metricsFromMeta(insights, nextMetrics);
          nextMetrics = mapped.metrics; imported = [...imported, ...mapped.imported];
          const highlights = metaHighlights(insights); if (highlights.length) nextHighlights = highlights;
          successes += 1;
          if (insights.status === "partial") warnings.push("dados orgânicos parciais");
        } else warnings.push("dados orgânicos indisponíveis");
      } else if (hasOrganic) warnings.push("falha ao importar dados orgânicos");

      if (adsResult.status === "fulfilled" && adsResult.value) {
        nextMetrics = { ...nextMetrics, ads: adsFromMeta(adsResult.value) };
        imported = [...imported, "ads.spend", "ads.reach", "ads.impressions", "ads.clicks", "ads.ctr", "ads.cpc", "ads.cpm"];
        successes += 1;
        if (adsResult.value.warnings.length) warnings.push("alguns dados de anúncios vieram com avisos");
      } else if (hasAds) warnings.push("falha ao importar Meta Ads");

      if (!successes) {
        setMessageTone("error"); setMessage("A Meta não retornou dados utilizáveis para este período. Nenhum campo existente foi apagado."); return;
      }
      setEditing({ ...editing, metrics: nextMetrics, highlights: nextHighlights });
      setImportedFields(imported);
      setMessageTone(warnings.length ? "warning" : "success");
      setMessage(warnings.length ? `Importação concluída com ressalvas: ${warnings.join(" · ")}.` : "Dados orgânicos e de anúncios importados da Meta com sucesso.");
    } catch (error) {
      const timedOut = error instanceof ApiRequestTimeoutError;
      setMessageTone(timedOut ? "timeout" : "error");
      setMessage(timedOut ? "A importação excedeu o tempo limite. Os dados existentes foram preservados." : error instanceof Error ? `Erro de API: ${error.message}` : "Erro de API: não foi possível concluir a importação da Meta.");
    } finally { setImportingMeta(false); }
  };
  const readScreenshots = async () => { if (!editing || !Object.keys(files).length) return; setReading(true); setMessage(""); try { const evidenceUrls = await Promise.all(Object.values(files).map(uploadAdminMedia)); const extracted = await extractAdminReportMetrics(clientId, evidenceUrls); setEditing({ ...editing, metrics: extracted.metrics, highlights: extracted.highlights, evidenceUrls: [...editing.evidenceUrls, ...evidenceUrls] }); setImportedFields([]); setMessageTone("success"); setMessage("Análise concluída. Revise os números e os conteúdos em destaque antes de salvar."); } catch (error) { setMessageTone("error"); setMessage(error instanceof Error ? error.message : "Não foi possível analisar as capturas. Você pode preencher os campos manualmente."); } finally { setReading(false); } };
  const changeMetric = (channel: "instagram" | "facebook", key: string, raw: string) => { if (!editing) return; const value = raw === "" ? null : Math.max(0, Number(raw) || 0); setEditing({ ...editing, metrics: { ...editing.metrics, [channel]: { ...editing.metrics[channel], [key]: value } } }); setImportedFields((current) => current.filter((field) => field !== `${channel}.${key}`)); };
  const save = async () => { if (!editing || !clientId || !editing.title.trim()) return; const payload = { title: editing.title.trim(), periodStart: reportDateValue(editing.periodStart), periodEnd: reportDateValue(editing.periodEnd), metrics: editing.metrics, highlights: editing.highlights, evidenceUrls: editing.evidenceUrls, notes: editing.notes }; try { const response = editing.id ? await updateAdminReport(clientId, editing.id, payload) : await createAdminReport(clientId, payload); setEditing(response.report); await refresh(); setMessageTone("success"); setMessage("Relatório salvo como rascunho."); } catch { const now = new Date().toISOString(); const localReport: ClientReport = editing.id ? { ...editing, ...payload, updatedAt: now } : { ...editing, ...payload, id: crypto.randomUUID(), clientAccountId: clientId, createdAt: now, updatedAt: now }; const next = [localReport, ...reports.filter((report) => report.id !== localReport.id)]; writeLocalReports(clientId, next); setReports(next); setEditing(localReport); setLocalMode(true); setMessageTone("warning"); setMessage("Rascunho salvo neste navegador."); } };
  const publish = async () => { if (!editing?.id) return; try { const response = await publishAdminReport(clientId, editing.id); setEditing(response.report); await refresh(); setMessageTone("success"); setMessage("Relatório publicado no portal do cliente."); } catch { const report = { ...editing, status: "published" as const, publishedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const next = reports.map((item) => item.id === report.id ? report : item); writeLocalReports(clientId, next); setReports(next); setEditing(report); setLocalMode(true); setMessageTone("warning"); setMessage("Relatório publicado nesta demonstração."); } };
  const linkedAccounts = [metaAssets?.instagramUsername ? `Instagram @${metaAssets.instagramUsername}` : null, metaAssets?.facebookPageName ? `Facebook ${metaAssets.facebookPageName}` : null, metaAssets?.metaAdAccountName ? `Ads ${metaAssets.metaAdAccountName}` : null].filter(Boolean);
  return <section className="reports-workspace"><div className="reports-client-picker"><label>Cliente<select value={clientId} onChange={(event) => setClientId(event.target.value)}>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><span>{reports.length} relatório{reports.length === 1 ? "" : "s"} neste cliente</span></div><div className="reports-layout"><aside className="reports-history"><h3>Histórico</h3>{reports.map((report) => <button key={report.id} className={editing?.id === report.id ? "selected" : ""} onClick={() => { setEditing(report); setFiles({}); setMessage(""); setImportedFields([]); }}><small>{report.status === "published" ? "Publicado" : "Rascunho"}</small><strong>{report.title}</strong><span>{formatReportDate(report.periodEnd)}</span></button>)}{!reports.length ? <p>Crie o primeiro relatório deste cliente.</p> : null}</aside><main>{editing ? <div className="report-editor">
    <div className="report-form-top"><label>Título<input value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })} /></label><label>De<input type="date" value={reportDateValue(editing.periodStart)} onChange={(event) => setEditing({ ...editing, periodStart: event.target.value })} /></label><label>Até<input type="date" value={reportDateValue(editing.periodEnd)} onChange={(event) => setEditing({ ...editing, periodEnd: event.target.value })} /></label></div>
    <section className="report-meta-import"><div className="report-meta-import-icon" aria-hidden="true">M</div><div><span>DADOS DA META</span><h3>Importar Insights do período <small className={metaStatus?.connected ? "connected" : ""}>{metaStatus?.connected ? "Conectada" : "Não conectada"}</small></h3><p>{formatReportDate(editing.periodStart)} – {formatReportDate(editing.periodEnd)} · {metaStatus?.connected ? linkedAccounts.length ? linkedAccounts.join(" · ") : "Nenhum Instagram ou Facebook vinculado a este cliente." : "Conecte a Meta e vincule os ativos deste cliente para importar dados automaticamente."}</p></div><button className="gradient-button" disabled={importingMeta || !metaStatus?.connected || !linkedAccounts.length} onClick={() => void importMeta()}>{importingMeta ? "Importando..." : "Importar dados da Meta"}</button></section>
    <section className="report-metrics-editor">{(["instagram", "facebook"] as const).map((channel) => <article key={channel}><h3>{channel === "instagram" ? "Instagram" : "Facebook"}</h3>{METRICS.map(([key, label]) => <label className={importedFields.includes(`${channel}.${key}`) ? "meta-imported" : ""} key={key}><span>{label}{importedFields.includes(`${channel}.${key}`) ? <small>Meta</small> : null}</span><input type="number" min="0" value={editing.metrics[channel][key] ?? ""} placeholder="Não disponível" onChange={(event) => changeMetric(channel, key, event.target.value)} /></label>)}{channel === "facebook" ? FACEBOOK_EXTRAS.map(([key, label]) => <label className={importedFields.includes(`facebook.${key}`) ? "meta-imported" : ""} key={key}><span>{label}{importedFields.includes(`facebook.${key}`) ? <small>Meta</small> : null}</span><input type="number" min="0" value={editing.metrics.facebook[key] ?? ""} placeholder="Não disponível" onChange={(event) => changeMetric("facebook", key, event.target.value)} /></label>) : null}</article>)}</section>
    {editing.metrics.ads ? <section className="report-ads-editor"><header><div><span>META ADS</span><h3>Dados pagos importados</h3><p>{editing.metrics.ads.accountName || "Conta de anúncios"}{editing.metrics.ads.currency ? ` · ${editing.metrics.ads.currency}` : ""}</p></div></header><div className="report-ads-kpis">{[["Investimento", currency(editing.metrics.ads.spend, editing.metrics.ads.currency, "pt")], ["Alcance pago", displayMetric(editing.metrics.ads.reach, "pt")], ["Impressões", displayMetric(editing.metrics.ads.impressions, "pt")], ["Cliques no link", displayMetric(editing.metrics.ads.inlineLinkClicks ?? editing.metrics.ads.clicks, "pt")], ["CTR", percent(editing.metrics.ads.ctr, "pt")], ["CPC", currency(editing.metrics.ads.cpc, editing.metrics.ads.currency, "pt")], ["CPM", currency(editing.metrics.ads.cpm, editing.metrics.ads.currency, "pt")], ["Frequência", decimal(editing.metrics.ads.frequency, "pt")]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div></section> : null}
    <details className="report-advanced"><summary>Opções avançadas · importar por screenshots</summary><section className="report-checklist"><header><div><span>FALLBACK POR IMAGEM</span><h3>Checklist de capturas</h3><p>Use esta opção quando os dados da Meta não estiverem disponíveis.</p></div><button className="ghost-button" disabled={reading || !Object.keys(files).length} onClick={() => void readScreenshots()}>{reading ? "Lendo capturas..." : "Analisar com IA"}</button></header>{(["instagram", "facebook"] as const).map((channel) => <div className="report-checklist-channel" key={channel}><strong>{channel === "instagram" ? "Instagram" : "Facebook"}</strong>{CHECKLIST.map((item) => { const key = `${channel}-${item}`; return <label key={key}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) setFiles({ ...files, [key]: file }); }} /><span>{files[key] ? "✓" : "+"}</span>{item}</label>; })}</div>)}</section></details>
    <label className="report-notes-editor">Observações da equipe<textarea value={editing.notes ?? ""} onChange={(event) => setEditing({ ...editing, notes: event.target.value || null })} placeholder="Contexto, campanhas ou pontos a destacar para o cliente." /></label>
    <div className="report-actions"><button className="ghost-button" onClick={() => setEditing(null)}>Fechar</button>{editing.id ? <button className="danger-button" onClick={() => { if (window.confirm("Excluir este relatório?")) void deleteAdminReport(clientId, editing.id).then(() => { setEditing(null); void refresh(); }).catch(() => { const next = reports.filter((report) => report.id !== editing.id); writeLocalReports(clientId, next); setReports(next); setEditing(null); }); }}>Excluir</button> : null}<button className="gradient-button" onClick={() => void save()}>Salvar rascunho</button>{editing.id && editing.status !== "published" ? <button className="gradient-button" onClick={() => void publish()}>Publicar para cliente</button> : null}</div>{message ? <p className={`report-message ${messageTone}`}>{message}</p> : null}<ReportDocument report={editing} clientName={selectedClient?.name ?? "Cliente"} />
  </div> : <div className="reports-empty">Escolha um relatório ou crie um novo para começar.</div>}</main></div></section>;
}

export function PortalReports({ slug, clientName, locale = "pt" }: { slug: string; clientName: string; locale?: string }) {
  const language = reportLocale(locale); const copy = reportText[language]; const [reports, setReports] = useState<ClientReport[]>([]); const [selected, setSelected] = useState<ClientReport | null>(null);
  useEffect(() => { void listPortalReportsBySlug(slug).then((response) => { setReports(response.items); setSelected(response.items[0] ?? null); }).catch(() => setReports([])); }, [slug]);
  return <section className="portal-reports"><header><div><span>{copy.results}</span><h1>{copy.reports}</h1><p>{copy.portalIntro}</p></div></header><div className="portal-reports-layout"><aside>{reports.map((report) => <button className={selected?.id === report.id ? "selected" : ""} key={report.id} onClick={() => setSelected(report)}><strong>{report.title}</strong><span>{formatReportDate(report.periodStart, language)} - {formatReportDate(report.periodEnd, language)}</span></button>)}{!reports.length ? <p>{copy.empty}</p> : null}</aside><main>{selected ? <><ReportDocument report={selected} clientName={clientName} locale={language} /><footer className="portal-report-download"><span aria-hidden="true">PDF</span><div><strong>{copy.download}</strong><p>{selected.title}</p></div><button className="gradient-button" onClick={() => void downloadReportPdf(selected, clientName, language)}>⇩ {copy.download}</button></footer></> : null}</main></div></section>;
}
