import { useEffect, useState } from "react";
import { jsPDF } from "jspdf";
import { createAdminReport, deleteAdminReport, extractAdminReportMetrics, listAdminClients, listAdminReports, listPortalReportsBySlug, publishAdminReport, updateAdminReport, uploadAdminMedia, type AdminClientOption, type ClientReport, type ReportMetrics } from "./api";

const METRICS = [
  ["reach", "Alcance", ["alcance", "accounts reached", "contas alcançadas", "pessoas alcançadas"]],
  ["impressions", "Impressões", ["impressões", "impressions", "visualizações", "visualizacoes", "views"]],
  ["engagement", "Engajamento", ["engajamento", "interações", "interacoes", "interactions", "envolvimento"]],
  ["followers", "Seguidores", ["seguidores", "followers", "total followers", "novos seguidores"]],
  ["visits", "Visitas", ["visitas ao perfil", "visitas", "profile visits", "acessos ao perfil"]],
  ["clicks", "Cliques", ["cliques", "clicks", "link clicks", "toques no link"]],
] as const;
const CHECKLIST = ["Visão geral", "Melhores conteúdos"];
const emptyMetrics = (): ReportMetrics => ({ instagram: { reach: 0, impressions: 0, engagement: 0, followers: 0, visits: 0, clicks: 0 }, facebook: { reach: 0, impressions: 0, engagement: 0, followers: 0, visits: 0, clicks: 0 } });
const fallbackClients: AdminClientOption[] = [{ id: "demo-aplikasi", name: "Aplikasi", slug: "aplikasi" }, { id: "demo-minas-home", name: "Minas Home ADS", slug: "minas-home-ads" }, { id: "demo-podcast", name: "Podcast Líder de Elite", slug: "podcast-lider-de-elite" }];
const dateValue = (date: Date) => date.toISOString().slice(0, 10);
type ReportLocale = "pt" | "en" | "es" | "it" | "sv";
const reportLocale = (locale?: string): ReportLocale => ["en", "es", "it", "sv"].includes(locale ?? "") ? locale as ReportLocale : "pt";
const browserLocale: Record<ReportLocale, string> = { pt: "pt-BR", en: "en-US", es: "es-ES", it: "it-IT", sv: "sv-SE" };
const reportText = {
  pt: { performance: "RELATÓRIO DE PERFORMANCE", published: "Publicado", draft: "Rascunho", summary: "Resumo geral", combined: "Instagram + Facebook", reachByChannel: "ALCANCE POR CANAL", comparison: "Comparativo de performance", highlights: "CONTEÚDOS EM DESTAQUE", teamNotes: "Notas da equipe", results: "RESULTADOS", reports: "Relatórios", portalIntro: "Acompanhe a performance das suas redes e baixe cada período em PDF.", download: "Baixar PDF", empty: "Nenhum relatório publicado ainda.", periodView: "VISÃO DO PERÍODO", reached: "contas alcançadas", consolidated: "Dados consolidados de Instagram e Facebook.", topContent: "CONTEÚDO EM DESTAQUE", generated: "Relatório gerado pela DesignHub", inPeriod: "no período, somando", acrossChannels: "contas alcançadas entre os canais.", bestContent: "O conteúdo em destaque foi" },
  en: { performance: "PERFORMANCE REPORT", published: "Published", draft: "Draft", summary: "Overview", combined: "Instagram + Facebook", reachByChannel: "REACH BY CHANNEL", comparison: "Performance comparison", highlights: "HIGHLIGHTED CONTENT", teamNotes: "Team notes", results: "RESULTS", reports: "Reports", portalIntro: "Track your social media performance and download each period as a PDF.", download: "Download PDF", empty: "No reports have been published yet.", periodView: "PERIOD OVERVIEW", reached: "accounts reached", consolidated: "Consolidated Instagram and Facebook data.", topContent: "TOP CONTENT", generated: "Report generated by DesignHub", inPeriod: "led reach in the period, totaling", acrossChannels: "accounts reached across channels.", bestContent: "The highlighted content was" },
  es: { performance: "INFORME DE RENDIMIENTO", published: "Publicado", draft: "Borrador", summary: "Resumen general", combined: "Instagram + Facebook", reachByChannel: "ALCANCE POR CANAL", comparison: "Comparativa de rendimiento", highlights: "CONTENIDO DESTACADO", teamNotes: "Notas del equipo", results: "RESULTADOS", reports: "Informes", portalIntro: "Sigue el rendimiento de tus redes y descarga cada período en PDF.", download: "Descargar PDF", empty: "Aún no hay informes publicados.", periodView: "RESUMEN DEL PERÍODO", reached: "cuentas alcanzadas", consolidated: "Datos consolidados de Instagram y Facebook.", topContent: "CONTENIDO DESTACADO", generated: "Informe generado por DesignHub", inPeriod: "lideró el alcance en el período, sumando", acrossChannels: "cuentas alcanzadas entre los canales.", bestContent: "El contenido destacado fue" },
  it: { performance: "REPORT DELLE PERFORMANCE", published: "Pubblicato", draft: "Bozza", summary: "Riepilogo generale", combined: "Instagram + Facebook", reachByChannel: "COPERTURA PER CANALE", comparison: "Confronto delle performance", highlights: "CONTENUTI IN EVIDENZA", teamNotes: "Note del team", results: "RISULTATI", reports: "Report", portalIntro: "Segui le performance dei tuoi social e scarica ogni periodo in PDF.", download: "Scarica PDF", empty: "Nessun report pubblicato.", periodView: "PANORAMICA DEL PERIODO", reached: "account raggiunti", consolidated: "Dati consolidati di Instagram e Facebook.", topContent: "CONTENUTO IN EVIDENZA", generated: "Report generato da DesignHub", inPeriod: "ha guidato la copertura nel periodo, per un totale di", acrossChannels: "account raggiunti sui canali.", bestContent: "Il contenuto in evidenza è stato" },
  sv: { performance: "PRESTANDARAPPORT", published: "Publicerad", draft: "Utkast", summary: "Sammanfattning", combined: "Instagram + Facebook", reachByChannel: "RÄCKVIDD PER KANAL", comparison: "Jämförelse av resultat", highlights: "UTVALT INNEHÅLL", teamNotes: "Teamets anteckningar", results: "RESULTAT", reports: "Rapporter", portalIntro: "Följ resultatet för dina sociala medier och ladda ner varje period som PDF.", download: "Ladda ner PDF", empty: "Inga rapporter har publicerats ännu.", periodView: "PERIODÖVERSIKT", reached: "nådda konton", consolidated: "Sammanställda data från Instagram och Facebook.", topContent: "BÄSTA INNEHÅLL", generated: "Rapport genererad av DesignHub", inPeriod: "hade högst räckvidd under perioden, totalt", acrossChannels: "nådda konton över kanalerna.", bestContent: "Det utvalda innehållet var" },
} as const;
const metricText: Record<ReportLocale, Record<string, string>> = { pt: { reach: "Alcance", impressions: "Impressões", engagement: "Engajamento", followers: "Seguidores", visits: "Visitas", clicks: "Cliques" }, en: { reach: "Reach", impressions: "Impressions", engagement: "Engagement", followers: "Followers", visits: "Visits", clicks: "Clicks" }, es: { reach: "Alcance", impressions: "Impresiones", engagement: "Interacción", followers: "Seguidores", visits: "Visitas", clicks: "Clics" }, it: { reach: "Copertura", impressions: "Impression", engagement: "Coinvolgimento", followers: "Follower", visits: "Visite", clicks: "Clic" }, sv: { reach: "Räckvidd", impressions: "Visningar", engagement: "Engagemang", followers: "Följare", visits: "Besök", clicks: "Klick" } };
const number = (value: number, locale: ReportLocale = "pt") => new Intl.NumberFormat(browserLocale[locale], { notation: value >= 10_000 ? "compact" : "standard", maximumFractionDigits: 1 }).format(value || 0);
const localReportKey = (clientId: string) => `designhub-v2-local-reports:${clientId}`;
const readLocalReports = (clientId: string): ClientReport[] => { try { return JSON.parse(window.localStorage.getItem(localReportKey(clientId)) ?? "[]") as ClientReport[]; } catch { return []; } };
const writeLocalReports = (clientId: string, reports: ClientReport[]) => window.localStorage.setItem(localReportKey(clientId), JSON.stringify(reports));

function reportSummary(report: Pick<ClientReport, "metrics" | "highlights">, locale: ReportLocale = "pt") {
  const instagram = report.metrics.instagram; const facebook = report.metrics.facebook;
  const winner = instagram.reach >= facebook.reach ? "Instagram" : "Facebook";
  const totalReach = instagram.reach + facebook.reach;
  const best = [...report.highlights].sort((a, b) => b.value - a.value)[0];
  const copy = reportText[locale];
  return `${winner} ${copy.inPeriod} ${number(totalReach, locale)} ${copy.acrossChannels}${best ? ` ${copy.bestContent} “${best.title}”.` : ""}`;
}

function metricFromText(text: string, aliases: readonly string[]) {
  const lines = text.toLocaleLowerCase("pt-BR").split("\n");
  for (let index = 0; index < lines.length; index += 1) {
    if (!aliases.some((alias) => lines[index].includes(alias))) continue;
    // Meta often places the label and its value on separate lines in a screenshot.
    const nearbyLines = lines.slice(Math.max(0, index - 1), index + 4);
    for (const line of nearbyLines) {
      const hit = line.match(/(?:\d{1,3}(?:[.\s]\d{3})+|\d+)(?:,\d+)?\s*(?:mil|k)?/i);
      if (!hit) continue;
      const raw = hit[0].toLocaleLowerCase().replace(/\s/g, "");
      const multiplier = /mil|k/.test(raw) ? 1_000 : 1;
      return Math.round(Number(raw.replace(/mil|k|\./g, "").replace(",", ".")) * multiplier);
    }
  }
  return null;
}

function ReportDocument({ report, clientName, locale = "pt", printable = false }: { report: ClientReport; clientName: string; locale?: string; printable?: boolean }) {
  const language = reportLocale(locale); const copy = reportText[language];
  const maxReach = Math.max(report.metrics.instagram.reach, report.metrics.facebook.reach, 1);
  return <article className={printable ? "report-document printable-report" : "report-document"}><header><div><span>{copy.performance}</span><h2>{clientName}</h2><p>{new Date(`${report.periodStart}T12:00`).toLocaleDateString(browserLocale[language])} a {new Date(`${report.periodEnd}T12:00`).toLocaleDateString(browserLocale[language])}</p></div><b>{report.status === "published" ? copy.published : copy.draft}</b></header><section className="report-summary"><strong>{copy.summary}</strong><p>{reportSummary(report, language)}</p></section><section className="report-kpis">{METRICS.slice(0, 4).map(([key]) => <article key={key}><span>{metricText[language][key]}</span><strong>{number(report.metrics.instagram[key] + report.metrics.facebook[key], language)}</strong><small>{copy.combined}</small></article>)}</section><section className="report-chart"><header><div><span>{copy.reachByChannel}</span><h3>{copy.comparison}</h3></div></header>{(["instagram", "facebook"] as const).map((channel) => <div className={`report-bar ${channel}`} key={channel}><span>{channel === "instagram" ? "Instagram" : "Facebook"}</span><i><b style={{ width: `${(report.metrics[channel].reach / maxReach) * 100}%` }} /></i><strong>{number(report.metrics[channel].reach, language)}</strong></div>)}</section><section className="report-detail-grid">{(["instagram", "facebook"] as const).map((channel) => <article key={channel}><h3>{channel === "instagram" ? "Instagram" : "Facebook"}</h3>{METRICS.slice(2).map(([key]) => <p key={key}><span>{metricText[language][key]}</span><b>{number(report.metrics[channel][key], language)}</b></p>)}</article>)}</section>{report.highlights.length ? <section className="report-highlights"><span>{copy.highlights}</span>{report.highlights.map((item, index) => <p key={`${item.title}-${index}`}><b>{index + 1}</b>{item.title}<em>{item.channel === "instagram" ? "Instagram" : "Facebook"} · {number(item.value, language)}</em></p>)}</section> : null}{report.notes ? <section className="report-notes"><strong>{copy.teamNotes}</strong><p>{report.notes}</p></section> : null}</article>;
}

function downloadReportPdf(report: ClientReport, clientName: string, locale = "pt") {
  const language = reportLocale(locale); const copy = reportText[language];
  const pdf = new jsPDF({ unit: "pt", format: "a4" });
  const width = 595;
  const contentX = 42;
  const cardWidth = 246;
  const totalReach = report.metrics.instagram.reach + report.metrics.facebook.reach;
  const maxReach = Math.max(report.metrics.instagram.reach, report.metrics.facebook.reach, 1);

  pdf.setFillColor(29, 39, 73);
  pdf.rect(0, 0, width, 842, "F");
  pdf.setFillColor(73, 88, 207);
  pdf.circle(535, 58, 112, "F");
  pdf.setFillColor(53, 190, 220);
  pdf.circle(502, 28, 74, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.text(copy.performance, contentX, 48);
  pdf.setFontSize(27);
  pdf.text(clientName, contentX, 79);
  pdf.setFontSize(11);
  pdf.text(`${new Date(`${report.periodStart}T12:00`).toLocaleDateString(browserLocale[language])} a ${new Date(`${report.periodEnd}T12:00`).toLocaleDateString(browserLocale[language])}`, contentX, 100);

  pdf.setFillColor(255, 255, 255);
  pdf.roundedRect(25, 128, 545, 668, 22, 22, "F");
  pdf.setTextColor(39, 51, 87);
  pdf.setFontSize(18);
  pdf.text(report.title, contentX, 164, { maxWidth: 490 });
  pdf.setTextColor(92, 106, 137);
  pdf.setFontSize(10);
  pdf.text(reportSummary(report, language), contentX, 192, { maxWidth: 475, lineHeightFactor: 1.45 });

  const kpis = METRICS.slice(0, 4);
  kpis.forEach(([key], index) => {
    const x = contentX + (index % 2) * 258;
    const y = 244 + Math.floor(index / 2) * 72;
    pdf.setFillColor(index % 2 ? 241 : 237, index % 2 ? 244 : 240, index % 2 ? 255 : 255);
    pdf.roundedRect(x, y, cardWidth, 57, 12, 12, "F");
    pdf.setTextColor(103, 117, 148);
    pdf.setFontSize(9);
    pdf.text(metricText[language][key].toUpperCase(), x + 13, y + 19);
    pdf.setTextColor(43, 54, 88);
    pdf.setFontSize(17);
    pdf.text(number(report.metrics.instagram[key] + report.metrics.facebook[key], language), x + 13, y + 43);
  });

  pdf.setTextColor(79, 91, 122);
  pdf.setFontSize(9);
  pdf.text(copy.reachByChannel, contentX, 357);
  pdf.setTextColor(39, 51, 87);
  pdf.setFontSize(16);
  pdf.text(copy.comparison, contentX, 380);
  (["instagram", "facebook"] as const).forEach((channel, index) => {
    const y = 412 + index * 42;
    const value = report.metrics[channel].reach;
    const fill = channel === "instagram" ? [229, 83, 153] : [54, 133, 233];
    pdf.setTextColor(84, 97, 128);
    pdf.setFontSize(11);
    pdf.text(channel === "instagram" ? "Instagram" : "Facebook", contentX, y);
    pdf.setFillColor(229, 233, 242);
    pdf.roundedRect(contentX + 92, y - 10, 300, 12, 6, 6, "F");
    pdf.setFillColor(fill[0], fill[1], fill[2]);
    pdf.roundedRect(contentX + 92, y - 10, Math.max(6, 300 * value / maxReach), 12, 6, 6, "F");
    pdf.setTextColor(39, 51, 87);
    pdf.setFontSize(11);
    pdf.text(number(value, language), 515, y, { align: "right" });
  });

  pdf.setFillColor(247, 249, 253);
  pdf.roundedRect(contentX, 510, 511, 142, 14, 14, "F");
  pdf.setTextColor(79, 91, 122);
  pdf.setFontSize(9);
  pdf.text(copy.periodView, contentX + 15, 534);
  pdf.setTextColor(39, 51, 87);
  pdf.setFontSize(17);
  pdf.text(`${number(totalReach, language)} ${copy.reached}`, contentX + 15, 560);
  pdf.setTextColor(100, 113, 143);
  pdf.setFontSize(10);
  pdf.text(copy.consolidated, contentX + 15, 581);
  if (report.highlights[0]) {
    pdf.setTextColor(79, 91, 122);
    pdf.setFontSize(9);
    pdf.text(copy.topContent, contentX + 15, 613);
    pdf.setTextColor(39, 51, 87);
    pdf.setFontSize(11);
    pdf.text(report.highlights[0].title, contentX + 15, 634, { maxWidth: 430 });
  }

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(9);
  pdf.text(copy.generated, contentX, 820);
  pdf.save(`${report.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`);
}

export function ReportsWorkspace({ newReportSignal = 0 }: { newReportSignal?: number }) {
  const [clients, setClients] = useState<AdminClientOption[]>(fallbackClients); const [clientId, setClientId] = useState(fallbackClients[0].id); const [reports, setReports] = useState<ClientReport[]>([]); const [editing, setEditing] = useState<ClientReport | null>(null); const [files, setFiles] = useState<Record<string, File>>({}); const [reading, setReading] = useState(false); const [message, setMessage] = useState(""); const [localMode, setLocalMode] = useState(false); const [ocrText, setOcrText] = useState(""); const [ocrProgress, setOcrProgress] = useState("");
  const selectedClient = clients.find((client) => client.id === clientId);
  const refresh = async (id = clientId) => { if (!id) return; try { const response = await listAdminReports(id); setReports(response.items); setLocalMode(false); } catch { setLocalMode(true); setReports(readLocalReports(id)); } };
  useEffect(() => { void listAdminClients().then((result) => { if (result.items.length) { setClients(result.items); setClientId(result.items[0].id); } }).catch(() => setLocalMode(true)); }, []);
  useEffect(() => { void refresh(); }, [clientId]);
  const newReport = () => { const end = new Date(); const start = new Date(); start.setDate(end.getDate() - 30); setFiles({}); setEditing({ id: "", clientAccountId: clientId, title: `Relatório ${selectedClient?.name ?? ""}`, periodStart: dateValue(start), periodEnd: dateValue(end), status: "draft", metrics: emptyMetrics(), highlights: [], evidenceUrls: [], notes: null, publishedAt: null, createdAt: "", updatedAt: "" }); };
  useEffect(() => { if (newReportSignal > 0) newReport(); }, [newReportSignal]);
  const readScreenshots = async () => { if (!editing || !Object.keys(files).length) return; setReading(true); setOcrProgress("Enviando capturas para análise..."); setMessage(""); try { const evidenceUrls = await Promise.all(Object.values(files).map(uploadAdminMedia)); setOcrProgress("Extraindo métricas com IA..."); const extracted = await extractAdminReportMetrics(clientId, evidenceUrls); setEditing({ ...editing, metrics: extracted.metrics, highlights: extracted.highlights, evidenceUrls: [...editing.evidenceUrls, ...evidenceUrls] }); setMessage("Análise concluída. Revise os números e os conteúdos em destaque antes de salvar."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível analisar as capturas. Você pode preencher os campos manualmente."); } finally { setReading(false); setOcrProgress(""); } };
  const save = async () => { if (!editing || !clientId || !editing.title.trim()) return; const payload = { title: editing.title.trim(), periodStart: editing.periodStart, periodEnd: editing.periodEnd, metrics: editing.metrics, highlights: editing.highlights, evidenceUrls: editing.evidenceUrls, notes: editing.notes }; try { const response = editing.id ? await updateAdminReport(clientId, editing.id, payload) : await createAdminReport(clientId, payload); setEditing(response.report); await refresh(); } catch { const now = new Date().toISOString(); const localReport: ClientReport = editing.id ? { ...editing, ...payload, updatedAt: now } : { ...editing, ...payload, id: crypto.randomUUID(), clientAccountId: clientId, createdAt: now, updatedAt: now }; const next = [localReport, ...reports.filter((report) => report.id !== localReport.id)]; writeLocalReports(clientId, next); setReports(next); setEditing(localReport); setLocalMode(true); } setMessage(localMode ? "Rascunho salvo neste navegador." : "Relatório salvo como rascunho."); };
  const publish = async () => { if (!editing?.id) return; try { const response = await publishAdminReport(clientId, editing.id); setEditing(response.report); await refresh(); setMessage("Relatório publicado no portal do cliente."); } catch { const report = { ...editing, status: "published" as const, publishedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; const next = reports.map((item) => item.id === report.id ? report : item); writeLocalReports(clientId, next); setReports(next); setEditing(report); setLocalMode(true); setMessage("Relatório publicado nesta demonstração."); } };
  return <section className="reports-workspace"><div className="reports-client-picker"><label>Cliente<select value={clientId} onChange={(event) => setClientId(event.target.value)}>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><span>{reports.length} relatório{reports.length === 1 ? "" : "s"} neste cliente</span></div><div className="reports-layout"><aside className="reports-history"><h3>Histórico</h3>{reports.map((report) => <button key={report.id} className={editing?.id === report.id ? "selected" : ""} onClick={() => { setEditing(report); setFiles({}); setMessage(""); }}><small>{report.status === "published" ? "Publicado" : "Rascunho"}</small><strong>{report.title}</strong><span>{new Date(`${report.periodEnd}T12:00`).toLocaleDateString("pt-BR")}</span></button>)}{!reports.length ? <p>Crie o primeiro relatório deste cliente.</p> : null}</aside><main>{editing ? <div className="report-editor"><div className="report-form-top"><label>Título<input value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })} /></label><label>De<input type="date" value={editing.periodStart} onChange={(event) => setEditing({ ...editing, periodStart: event.target.value })} /></label><label>Até<input type="date" value={editing.periodEnd} onChange={(event) => setEditing({ ...editing, periodEnd: event.target.value })} /></label></div><section className="report-checklist"><header><div><span>IMPORTAÇÃO GRATUITA</span><h3>Checklist de capturas</h3><p>Envie as telas do Instagram e Facebook. A leitura ocorre somente neste navegador.</p></div><button className="ghost-button" disabled={reading || !Object.keys(files).length} onClick={() => void readScreenshots()}>{reading ? "Lendo capturas..." : "Ler capturas"}</button></header>{(["instagram", "facebook"] as const).map((channel) => <div className="report-checklist-channel" key={channel}><strong>{channel === "instagram" ? "Instagram" : "Facebook"}</strong>{CHECKLIST.map((item) => { const key = `${channel}-${item}`; return <label key={key}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) setFiles({ ...files, [key]: file }); }} /><span>{files[key] ? "✓" : "+"}</span>{item}</label>; })}</div>)}</section><section className="report-metrics-editor">{(["instagram", "facebook"] as const).map((channel) => <article key={channel}><h3>{channel === "instagram" ? "Instagram" : "Facebook"}</h3>{METRICS.map(([key, label]) => <label key={key}>{label}<input type="number" min="0" value={editing.metrics[channel][key]} onChange={(event) => setEditing({ ...editing, metrics: { ...editing.metrics, [channel]: { ...editing.metrics[channel], [key]: Number(event.target.value) || 0 } } })} /></label>)}</article>)}</section><label className="report-notes-editor">Observações da equipe<textarea value={editing.notes ?? ""} onChange={(event) => setEditing({ ...editing, notes: event.target.value || null })} placeholder="Contexto, campanhas ou pontos a destacar para o cliente." /></label><div className="report-actions"><button className="ghost-button" onClick={() => setEditing(null)}>Fechar</button>{editing.id ? <button className="danger-button" onClick={() => { if (window.confirm("Excluir este relatório?")) void deleteAdminReport(clientId, editing.id).then(() => { setEditing(null); void refresh(); }).catch(() => { const next = reports.filter((report) => report.id !== editing.id); writeLocalReports(clientId, next); setReports(next); setEditing(null); }); }}>Excluir</button> : null}<button className="gradient-button" onClick={() => void save()}>Salvar rascunho</button>{editing.id && editing.status !== "published" ? <button className="gradient-button" onClick={() => void publish()}>Publicar para cliente</button> : null}</div>{message ? <p className="report-message">{message}</p> : null}<ReportDocument report={editing} clientName={selectedClient?.name ?? "Cliente"} /></div> : <div className="reports-empty">Escolha um relatório ou crie um novo para começar.</div>}</main></div></section>;
}

export function PortalReports({ slug, clientName, locale = "pt" }: { slug: string; clientName: string; locale?: string }) {
  const language = reportLocale(locale); const copy = reportText[language];
  const [reports, setReports] = useState<ClientReport[]>([]); const [selected, setSelected] = useState<ClientReport | null>(null);
  useEffect(() => { void listPortalReportsBySlug(slug).then((response) => { setReports(response.items); setSelected(response.items[0] ?? null); }).catch(() => setReports([])); }, [slug]);
  const download = () => { if (selected) downloadReportPdf(selected, clientName, language); };
  return <section className="portal-reports"><header><div><span>{copy.results}</span><h1>{copy.reports}</h1><p>{copy.portalIntro}</p></div>{selected ? <button className="gradient-button" onClick={download}>⇩ {copy.download}</button> : null}</header><div className="portal-reports-layout"><aside>{reports.map((report) => <button className={selected?.id === report.id ? "selected" : ""} key={report.id} onClick={() => setSelected(report)}><strong>{report.title}</strong><span>{new Date(`${report.periodStart}T12:00`).toLocaleDateString(browserLocale[language])} - {new Date(`${report.periodEnd}T12:00`).toLocaleDateString(browserLocale[language])}</span></button>)}{!reports.length ? <p>{copy.empty}</p> : null}</aside><main>{selected ? <ReportDocument report={selected} clientName={clientName} locale={language} /> : null}</main></div></section>;
}
