import crypto from "node:crypto";
import type { Pool, ResultSetHeader, RowDataPacket } from "mysql2/promise";
import type { CreateReportInput, UpdateReportInput } from "./reports.schemas.js";

type ReportRow = RowDataPacket & { id: string; client_account_id: string; title: string; period_start: string; period_end: string; status: "draft" | "published"; metrics_json: unknown; highlights_json: unknown; evidence_urls_json: unknown; notes: string | null; published_at: string | null; created_at: string; updated_at: string };
const columns = "id, client_account_id, title, period_start, period_end, status, metrics_json, highlights_json, evidence_urls_json, notes, published_at, created_at, updated_at";
const parse = <T>(value: unknown, fallback: T): T => { if (typeof value === "string") { try { return JSON.parse(value) as T; } catch { return fallback; } } return (value as T) ?? fallback; };
const map = (row: ReportRow) => ({ id: row.id, clientAccountId: row.client_account_id, title: row.title, periodStart: row.period_start, periodEnd: row.period_end, status: row.status, metrics: parse(row.metrics_json, { instagram: {}, facebook: {} }), highlights: parse(row.highlights_json, []), evidenceUrls: parse(row.evidence_urls_json, []), notes: row.notes, publishedAt: row.published_at, createdAt: row.created_at, updatedAt: row.updated_at });

export async function listReports(db: Pool, clientAccountId: string, publishedOnly = false) { const [rows] = await db.query<ReportRow[]>(`SELECT ${columns} FROM client_reports WHERE client_account_id = ?${publishedOnly ? " AND status = 'published'" : ""} ORDER BY period_end DESC, created_at DESC`, [clientAccountId]); return rows.map(map); }
export async function findReport(db: Pool, id: string) { const [rows] = await db.query<ReportRow[]>(`SELECT ${columns} FROM client_reports WHERE id = ? LIMIT 1`, [id]); return rows[0] ? map(rows[0]) : null; }
export async function createReport(db: Pool, clientAccountId: string, userId: string, input: CreateReportInput) { const id = crypto.randomUUID(); await db.query("INSERT INTO client_reports (id, client_account_id, title, period_start, period_end, metrics_json, highlights_json, evidence_urls_json, notes, created_by_user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [id, clientAccountId, input.title, input.periodStart, input.periodEnd, JSON.stringify(input.metrics), JSON.stringify(input.highlights), JSON.stringify(input.evidenceUrls), input.notes ?? null, userId]); return findReport(db, id); }
export async function updateReport(db: Pool, id: string, input: UpdateReportInput) { const fields: string[] = []; const params: unknown[] = []; const entries: Array<[keyof UpdateReportInput, string, boolean]> = [["title", "title", false], ["periodStart", "period_start", false], ["periodEnd", "period_end", false], ["metrics", "metrics_json", true], ["highlights", "highlights_json", true], ["evidenceUrls", "evidence_urls_json", true], ["notes", "notes", false]]; for (const [key, column, json] of entries) if (typeof input[key] !== "undefined") { fields.push(`${column} = ?`); params.push(json ? JSON.stringify(input[key]) : input[key]); } if (fields.length) { params.push(id); await db.query(`UPDATE client_reports SET ${fields.join(", ")} WHERE id = ?`, params); } return findReport(db, id); }
export async function publishReport(db: Pool, id: string) { await db.query("UPDATE client_reports SET status = 'published', published_at = NOW() WHERE id = ?", [id]); return findReport(db, id); }
export async function deleteReport(db: Pool, id: string) { const [result] = await db.query<ResultSetHeader>("DELETE FROM client_reports WHERE id = ?", [id]); return result.affectedRows > 0; }
