import type { FastifyPluginAsync } from "fastify";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { assertClientAccess, assertInternalAccess } from "../auth/auth.access.js";
import { findClientPermissionsByAccountId } from "../clients/clients.repository.js";
import { createReportSchema, updateReportSchema } from "./reports.schemas.js";
import { createReport, deleteReport, findReport, listReports, publishReport, updateReport } from "./reports.repository.js";

async function ownedReport(app: Parameters<FastifyPluginAsync>[0], clientAccountId: string, reportId: string, publishedOnly = false) { const report = await findReport(app.db, reportId); if (!report || report.clientAccountId !== clientAccountId || (publishedOnly && report.status !== "published")) throw app.httpErrors.notFound("Relatório não encontrado nesta conta."); return report; }

const extractionSchema = { type: "object", additionalProperties: false, required: ["metrics", "highlights"], properties: { metrics: { type: "object", additionalProperties: false, required: ["instagram", "facebook"], properties: { instagram: { type: "object", additionalProperties: false, required: ["reach", "impressions", "engagement", "followers", "visits", "clicks"], properties: { reach: { type: "number" }, impressions: { type: "number" }, engagement: { type: "number" }, followers: { type: "number" }, visits: { type: "number" }, clicks: { type: "number" } } }, facebook: { type: "object", additionalProperties: false, required: ["reach", "impressions", "engagement", "followers", "visits", "clicks"], properties: { reach: { type: "number" }, impressions: { type: "number" }, engagement: { type: "number" }, followers: { type: "number" }, visits: { type: "number" }, clicks: { type: "number" } } } } }, highlights: { type: "array", maxItems: 6, items: { type: "object", additionalProperties: false, required: ["channel", "title", "value"], properties: { channel: { type: "string", enum: ["instagram", "facebook"] }, title: { type: "string" }, value: { type: "number" } } } } } } as const;

async function extractWithOpenAi(app: Parameters<FastifyPluginAsync>[0], evidenceUrls: string[]) {
  if (!app.appEnv.OPENAI_API_KEY) throw app.httpErrors.badRequest("A leitura por IA ainda não foi configurada. Adicione OPENAI_API_KEY ao arquivo .env da API.");
  if (!evidenceUrls.length || evidenceUrls.length > 4) throw app.httpErrors.badRequest("Envie de uma a quatro capturas para análise.");
  const images = await Promise.all(evidenceUrls.map(async (url) => { const match = /^\/api\/uploads\/([a-f0-9-]+\.webp)$/.exec(url); if (!match) throw app.httpErrors.badRequest("Uma das imagens enviadas não é válida."); const data = await readFile(path.resolve(process.cwd(), app.appEnv.UPLOAD_DIR, match[1])); return { type: "input_image", image_url: `data:image/webp;base64,${data.toString("base64")}`, detail: "high" }; }));
  const response = await fetch("https://api.openai.com/v1/responses", { method: "POST", headers: { Authorization: `Bearer ${app.appEnv.OPENAI_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify({ model: "gpt-4.1-mini", input: [{ role: "user", content: [{ type: "input_text", text: "Leia estas capturas do Meta Business Suite. Extraia apenas números claramente visíveis. Não estime: use 0 quando uma métrica não estiver nas capturas. Para alcance, converta '33,5 mil' em 33500. Retorne também até seis conteúdos em destaque que estiverem visíveis." }, ...images] }], text: { format: { type: "json_schema", name: "report_metrics", strict: true, schema: extractionSchema } } }) });
  if (!response.ok) { const error = await response.text(); app.log.error({ error }, "OpenAI report extraction failed"); throw app.httpErrors.badRequest("Não foi possível analisar as capturas agora. Tente novamente."); }
  const result = await response.json() as { output_text?: string; output?: Array<{ content?: Array<{ text?: string }> }> }; const output = result.output_text ?? result.output?.flatMap((item) => item.content ?? []).map((item) => item.text ?? "").join(""); if (!output) throw app.httpErrors.badRequest("A IA não retornou dados para as capturas enviadas."); return JSON.parse(output);
}

export const reportRoutes: FastifyPluginAsync = async (app) => {
  app.get("/clients/:clientAccountId/reports", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); return { items: await listReports(app.db, p.clientAccountId) }; });
  app.post("/clients/:clientAccountId/reports", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); return { report: await createReport(app.db, p.clientAccountId, request.auth!.user.id, createReportSchema.parse(request.body)) }; });
  app.post("/clients/:clientAccountId/reports/extract", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); const body = request.body as { evidenceUrls?: unknown }; if (!Array.isArray(body.evidenceUrls) || !body.evidenceUrls.every((item) => typeof item === "string")) throw app.httpErrors.badRequest("Envie as capturas para análise."); return await extractWithOpenAi(app, body.evidenceUrls); });
  app.patch("/clients/:clientAccountId/reports/:reportId", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string; reportId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); await ownedReport(app, p.clientAccountId, p.reportId); return { report: await updateReport(app.db, p.reportId, updateReportSchema.parse(request.body)) }; });
  app.post("/clients/:clientAccountId/reports/:reportId/publish", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string; reportId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); await ownedReport(app, p.clientAccountId, p.reportId); return { report: await publishReport(app.db, p.reportId) }; });
  app.delete("/clients/:clientAccountId/reports/:reportId", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string; reportId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); await ownedReport(app, p.clientAccountId, p.reportId); return { ok: await deleteReport(app.db, p.reportId) }; });
  app.get("/portal/accounts/:clientAccountId/reports", async (request) => { const p = request.params as { clientAccountId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador", "cliente"]); const permissions = await findClientPermissionsByAccountId(app.db, p.clientAccountId); if (!permissions?.allowClientViewReports) throw app.httpErrors.forbidden("Relatórios não estão liberados para este cliente."); return { items: await listReports(app.db, p.clientAccountId, true) }; });
};
