import crypto from "node:crypto";
import type { Pool, ResultSetHeader, RowDataPacket } from "mysql2/promise";
import type { CreateTextInput, UpdateTextInput } from "./texts.schemas.js";

type StoredTextTag = string | { name?: unknown; color?: unknown };
type TextRow = RowDataPacket & { id: string; client_account_id: string; title: string; content_html: string; content_type: string; status: string; tags_json: string | StoredTextTag[] | null; cover_image_url: string | null; planned_at: string | null; internal_notes: string | null; is_sent_to_client: number; sent_at: string | null; created_by_user_id: string | null; created_at: string; updated_at: string };
type CommentRow = RowDataPacket & { id: string; text_id: string; user_id: string | null; author_name: string; author_role: string; comment_text: string; is_internal: number; author_avatar_url: string | null; created_at: string; updated_at: string };
const columns = "id, client_account_id, title, content_html, content_type, status, tags_json, cover_image_url, planned_at, internal_notes, is_sent_to_client, sent_at, created_by_user_id, created_at, updated_at";
const tagsFromDatabase = (value: TextRow["tags_json"]) => { try { const parsed = typeof value === "string" ? JSON.parse(value) : value; if (!Array.isArray(parsed)) return []; return parsed.flatMap((item) => { if (typeof item === "string" && item.trim()) return [{ name: item.trim(), color: "#7568dc" }]; if (item && typeof item === "object" && typeof item.name === "string" && item.name.trim()) return [{ name: item.name.trim(), color: typeof item.color === "string" && /^#[0-9a-fA-F]{6}$/.test(item.color) ? item.color : "#7568dc" }]; return []; }); } catch { return []; } };
const mapText = (row: TextRow) => ({ id: row.id, clientAccountId: row.client_account_id, title: row.title, contentHtml: row.content_html, contentType: row.content_type, status: row.status, tags: tagsFromDatabase(row.tags_json), coverImageUrl: row.cover_image_url, plannedAt: row.planned_at, internalNotes: row.internal_notes, isSentToClient: Boolean(row.is_sent_to_client), sentAt: row.sent_at, createdByUserId: row.created_by_user_id, createdAt: row.created_at, updatedAt: row.updated_at });
const mapComment = (row: CommentRow) => ({ id: row.id, textId: row.text_id, userId: row.user_id, authorName: row.author_name, authorRole: row.author_role, authorAvatarUrl: row.author_avatar_url, commentText: row.comment_text, isInternal: Boolean(row.is_internal), createdAt: row.created_at, updatedAt: row.updated_at });

const preparedPools = new WeakSet<Pool>();
async function ensureTextStorage(db: Pool) {
  if (preparedPools.has(db)) return;
  const [tagRows] = await db.query<RowDataPacket[]>("SHOW COLUMNS FROM client_texts LIKE 'tags_json'");
  if (!tagRows.length) await db.query("ALTER TABLE client_texts ADD COLUMN tags_json JSON NULL AFTER status");
  const [coverRows] = await db.query<RowDataPacket[]>("SHOW COLUMNS FROM client_texts LIKE 'cover_image_url'");
  if (!coverRows.length) await db.query("ALTER TABLE client_texts ADD COLUMN cover_image_url VARCHAR(2048) NULL AFTER tags_json");
  preparedPools.add(db);
}
export async function listTexts(db: Pool, clientAccountId: string, sentOnly = false) { await ensureTextStorage(db); const [rows] = await db.query<TextRow[]>(`SELECT ${columns} FROM client_texts WHERE client_account_id = ?${sentOnly ? " AND is_sent_to_client = 1" : ""} ORDER BY updated_at DESC`, [clientAccountId]); return rows.map(mapText); }
export async function findText(db: Pool, textId: string) { await ensureTextStorage(db); const [rows] = await db.query<TextRow[]>(`SELECT ${columns} FROM client_texts WHERE id = ? LIMIT 1`, [textId]); return rows[0] ? mapText(rows[0]) : null; }
export async function createText(db: Pool, clientAccountId: string, userId: string, input: CreateTextInput) { await ensureTextStorage(db); const id = crypto.randomUUID(); await db.query("INSERT INTO client_texts (id, client_account_id, title, content_html, content_type, tags_json, cover_image_url, created_by_user_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", [id, clientAccountId, input.title, input.contentHtml, input.contentType, JSON.stringify(input.tags), input.coverImageUrl ?? null, userId]); return findText(db, id); }
export async function updateText(db: Pool, textId: string, input: UpdateTextInput) { await ensureTextStorage(db); const fields: string[] = []; const params: Array<string | null> = []; const mappings: Array<[keyof UpdateTextInput, string]> = [["title", "title"], ["contentHtml", "content_html"], ["contentType", "content_type"], ["coverImageUrl", "cover_image_url"], ["plannedAt", "planned_at"], ["internalNotes", "internal_notes"], ["status", "status"]]; for (const [key, field] of mappings) if (typeof input[key] !== "undefined") { fields.push(`${field} = ?`); params.push(input[key] as string | null); } if (typeof input.tags !== "undefined") { fields.push("tags_json = ?"); params.push(JSON.stringify(input.tags)); } if (fields.length) { params.push(textId); await db.query(`UPDATE client_texts SET ${fields.join(", ")} WHERE id = ?`, params); } return findText(db, textId); }
export async function sendText(db: Pool, textId: string) { await db.query("UPDATE client_texts SET is_sent_to_client = 1, sent_at = NOW(), status = 'Em revisão' WHERE id = ?", [textId]); return findText(db, textId); }
export async function deleteText(db: Pool, textId: string) { const [result] = await db.query<ResultSetHeader>("DELETE FROM client_texts WHERE id = ?", [textId]); return result.affectedRows > 0; }
export async function listTextComments(db: Pool, textId: string, includeInternal: boolean) { const [rows] = await db.query<CommentRow[]>(`SELECT tc.id, tc.text_id, tc.user_id, tc.author_name, tc.author_role, tc.comment_text, tc.is_internal, tc.created_at, tc.updated_at, COALESCE(u.avatar_url, CASE WHEN tc.author_role = 'cliente' THEN ca.logo_url ELSE NULL END) AS author_avatar_url FROM text_comments tc INNER JOIN client_texts ct ON ct.id = tc.text_id INNER JOIN client_accounts ca ON ca.id = ct.client_account_id LEFT JOIN users u ON u.id = tc.user_id WHERE tc.text_id = ?${includeInternal ? "" : " AND tc.is_internal = 0"} ORDER BY tc.created_at ASC`, [textId]); return rows.map(mapComment); }
export async function createTextComment(db: Pool, input: { textId: string; userId: string | null; authorName: string; authorRole: string; commentText: string; isInternal: boolean }) { const id = crypto.randomUUID(); await db.query("INSERT INTO text_comments (id, text_id, user_id, author_name, author_role, comment_text, is_internal) VALUES (?, ?, ?, ?, ?, ?, ?)", [id, input.textId, input.userId, input.authorName, input.authorRole, input.commentText, input.isInternal ? 1 : 0]); const comments = await listTextComments(db, input.textId, true); return comments.find((comment) => comment.id === id) ?? null; }
