import type { FastifyPluginAsync } from "fastify";
import { assertClientAccess, assertInternalAccess } from "../auth/auth.access.js";
import { createTextCommentSchema, createTextSchema, textDecisionSchema, updateTextSchema } from "./texts.schemas.js";
import { createText, createTextComment, deleteText, findText, listTextComments, listTexts, sendText, updateText } from "./texts.repository.js";

async function ownedText(app: Parameters<FastifyPluginAsync>[0], clientAccountId: string, textId: string, sentOnly = false) { const text = await findText(app.db, textId); if (!text || text.clientAccountId !== clientAccountId || (sentOnly && !text.isSentToClient)) throw app.httpErrors.notFound("Texto não encontrado nesta conta."); return text; }

export const textRoutes: FastifyPluginAsync = async (app) => {
  app.get("/clients/:clientAccountId/texts", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); return { items: await listTexts(app.db, p.clientAccountId) }; });
  app.post("/clients/:clientAccountId/texts", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); return { text: await createText(app.db, p.clientAccountId, request.auth!.user.id, createTextSchema.parse(request.body)) }; });
  app.patch("/clients/:clientAccountId/texts/:textId", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string; textId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); await ownedText(app, p.clientAccountId, p.textId); return { text: await updateText(app.db, p.textId, updateTextSchema.parse(request.body)) }; });
  app.delete("/clients/:clientAccountId/texts/:textId", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string; textId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); await ownedText(app, p.clientAccountId, p.textId); return { ok: await deleteText(app.db, p.textId) }; });
  app.post("/clients/:clientAccountId/texts/:textId/send", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string; textId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); await ownedText(app, p.clientAccountId, p.textId); return { text: await sendText(app.db, p.textId) }; });
  app.get("/clients/:clientAccountId/texts/:textId/comments", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string; textId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); await ownedText(app, p.clientAccountId, p.textId); return { comments: await listTextComments(app.db, p.textId, true) }; });
  app.post("/clients/:clientAccountId/texts/:textId/comments", async (request) => { assertInternalAccess(request); const p = request.params as { clientAccountId: string; textId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador"]); await ownedText(app, p.clientAccountId, p.textId); const input = createTextCommentSchema.parse(request.body); const user = request.auth!.user; return { comment: await createTextComment(app.db, { textId: p.textId, userId: user.id, authorName: user.fullName, authorRole: user.globalRole, ...input }) }; });
  app.get("/portal/accounts/:clientAccountId/texts", async (request) => { const p = request.params as { clientAccountId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador", "cliente"]); return { items: await listTexts(app.db, p.clientAccountId, true) }; });
  app.get("/portal/accounts/:clientAccountId/texts/:textId/comments", async (request) => { const p = request.params as { clientAccountId: string; textId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador", "cliente"]); await ownedText(app, p.clientAccountId, p.textId, true); return { comments: await listTextComments(app.db, p.textId, false) }; });
  app.post("/portal/accounts/:clientAccountId/texts/:textId/comments", async (request) => { const p = request.params as { clientAccountId: string; textId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador", "cliente"]); await ownedText(app, p.clientAccountId, p.textId, true); const input = createTextCommentSchema.parse(request.body); const user = request.auth!.user; return { comment: await createTextComment(app.db, { textId: p.textId, userId: user.id, authorName: user.fullName, authorRole: user.globalRole, commentText: input.commentText, isInternal: false }) }; });
  app.post("/portal/accounts/:clientAccountId/texts/:textId/decision", async (request) => { const p = request.params as { clientAccountId: string; textId: string }; assertClientAccess(request, p.clientAccountId, ["admin", "colaborador", "cliente"]); await ownedText(app, p.clientAccountId, p.textId, true); const input = textDecisionSchema.parse(request.body); const user = request.auth!.user; if (input.commentText?.trim()) await createTextComment(app.db, { textId: p.textId, userId: user.id, authorName: user.fullName, authorRole: user.globalRole, commentText: input.commentText.trim(), isInternal: false }); const text = await updateText(app.db, p.textId, { status: input.approved ? "Aprovado" : "Em revisão" }); return { text }; });
};
