-- Checkpoint 1: additive only; apply explicitly after review. No runtime DDL.
-- Source dates retain the publisher's date precision (ISO date or ISO timestamp).
CREATE TABLE IF NOT EXISTS radar_suggestions (
  id CHAR(36) NOT NULL PRIMARY KEY,
  client_account_id CHAR(36) NOT NULL,
  title VARCHAR(240) NOT NULL,
  concept TEXT NOT NULL,
  hook TEXT NOT NULL,
  description TEXT NOT NULL,
  content_type VARCHAR(80) NOT NULL,
  pillar VARCHAR(240) NULL,
  objective TEXT NOT NULL,
  rationale TEXT NOT NULL,
  cta TEXT NULL,
  caption_suggestion MEDIUMTEXT NULL,
  alignment_score TINYINT UNSIGNED NULL,
  source_title VARCHAR(500) NOT NULL,
  source_url TEXT NULL,
  source_date VARCHAR(40) NULL,
  radar_name VARCHAR(240) NOT NULL,
  ai_model VARCHAR(120) NULL,
  based_on_json JSON NOT NULL,
  brand_brain_version INT UNSIGNED NULL,
  brand_brain_context_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  source_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  dedupe_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  created_by_user_id CHAR(36) NULL,
  accepted_pauta_id CHAR(36) NULL,
  accepted_by_user_id CHAR(36) NULL,
  dismissed_by_user_id CHAR(36) NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  accepted_at TIMESTAMP(3) NULL DEFAULT NULL,
  dismissed_at TIMESTAMP(3) NULL DEFAULT NULL,
  UNIQUE KEY uq_radar_suggestion_client_dedupe (client_account_id, dedupe_hash),
  KEY idx_radar_suggestion_client_status_created (client_account_id, status, created_at, id),
  KEY idx_radar_suggestion_client_source (client_account_id, source_key),
  KEY idx_radar_suggestion_status_created (status, created_at, id),
  CONSTRAINT fk_radar_suggestion_client FOREIGN KEY (client_account_id) REFERENCES client_accounts(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_radar_suggestion_creator FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_radar_suggestion_acceptor FOREIGN KEY (accepted_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT fk_radar_suggestion_dismisser FOREIGN KEY (dismissed_by_user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT chk_radar_suggestion_status CHECK (status IN ('pending', 'accepted', 'dismissed')),
  CONSTRAINT chk_radar_suggestion_alignment CHECK (alignment_score IS NULL OR alignment_score <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
