import assert from "node:assert/strict";
import { test, before, after } from "node:test";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import mysql, { type RowDataPacket } from "mysql2/promise";
import Fastify from "fastify";
import { httpErrorsPluginRegistered } from "../../plugins/http-errors.js";
import { clientRoutes } from "../clients/clients.routes.js";
import { BrandBrainAiRepository } from "./brand-brain-ai.repository.js";
import { BrandBrainAiService } from "./brand-brain-ai.service.js";
const socketPath = process.env.RADAR_TEST_SOCKET;
if (!socketPath || !/^\/(?:private\/)?tmp\/radar-mariadb-[^/]+\/server\.sock$/.test(socketPath)) throw Error("Use apenas o socket temporário /tmp/radar-mariadb-*/server.sock.");
const parsed = (value: unknown): any => typeof value === "string" ? JSON.parse(value) : value;
const schema = readFileSync(new URL("../../../db/schema.sql", import.meta.url), "utf8").split("-- Additive foundation only.")[0];
const migration = readFileSync(new URL("../../../../../database/migrations/20261007_brand_brain_ai_runs.sql", import.meta.url), "utf8");
let server: mysql.Connection;
before(async () => { server = await mysql.createConnection({ socketPath, user: "root", multipleStatements: true }); }); after(async () => { await server?.end(); });
async function fixture() {
  const database = `brand_ai_test_${randomUUID().replace(/-/g, "")}`; await server.query(`CREATE DATABASE \`${database}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  const pool = mysql.createPool({ socketPath, user: "root", database, multipleStatements: true, timezone: "Z", connectionLimit: 8 }); const close = async () => { await pool.end(); await server.query(`DROP DATABASE \`${database}\``); };
  try { await pool.query(schema); const clientId = randomUUID(); const drawer = { brandBrain: { voice: "Publicado 🐕", positioning: "Oficial", avoidWords: ["domine"] }, links: [{ url: "https://example.org" }], futureField: { nested: [1, 2] }, automations: ["keep"], pautaIdeas: [{ id: "legacy", title: "Antiga", status: "approved" }] }; await pool.query("INSERT INTO client_accounts (id,name,slug,locale,portal_title,workspace_drawer_json) VALUES (?, 'A', 'a', 'it-IT', 'Portal', ?)", [clientId, JSON.stringify(drawer)]); await pool.query(migration); return { pool, database, clientId, drawer, close }; } catch (error) { await close(); throw error; }
}
test("MariaDB: additive repeatable telemetry migration, indexes/FK/defaults and untouched legacy", async () => {
  const f = await fixture(); try { await f.pool.query(migration); const query = async (sql: string, params: unknown[] = []) => (await f.pool.query<RowDataPacket[]>(sql, params))[0]; console.log(`Temporary MariaDB: ${(await query("SELECT VERSION() AS version"))[0].version}`);
    const columns = await query("SELECT COLUMN_NAME,COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=? AND TABLE_NAME='brand_brain_ai_runs'", [f.database]); assert.equal(columns.length, 13); assert.equal(columns.find(c => c.COLUMN_NAME === "created_at")!.COLUMN_TYPE, "timestamp(3)"); assert.ok((await query("SHOW INDEX FROM brand_brain_ai_runs")).some(i => i.Key_name === "idx_brand_ai_client_created"));
    const fk = await query("SELECT DELETE_RULE,UPDATE_RULE FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=? AND TABLE_NAME='brand_brain_ai_runs'", [f.database]); assert.equal(fk.length, 1); assert.equal(fk[0].DELETE_RULE, "RESTRICT"); assert.equal(fk[0].UPDATE_RULE, "RESTRICT"); const repo = new BrandBrainAiRepository(f.pool); const id = await repo.beginRun(f.clientId, "analyze", "gpt-4.1-mini", "a".repeat(64)); const run = (await query("SELECT * FROM brand_brain_ai_runs WHERE id=?", [id]))[0]; assert.equal(run.status, "running"); assert.equal(run.estimated_cost_usd, null); assert.equal(run.total_tokens, null); await assert.rejects(f.pool.query("UPDATE brand_brain_ai_runs SET status='unknown'")); await assert.rejects(f.pool.query("DELETE FROM client_accounts WHERE id=?", [f.clientId]));
    assert.deepEqual(parsed((await query("SELECT workspace_drawer_json FROM client_accounts WHERE id=?", [f.clientId]))[0].workspace_drawer_json), f.drawer);
  } finally { await f.close(); }
});
test("MariaDB: official context and usage recorded with a mock provider, no pauta/card writes", async () => {
  const f = await fixture(); try { const repo = new BrandBrainAiRepository(f.pool); const client = await repo.officialClient(f.clientId); assert.equal(client!.brain.voice, "Publicado 🐕"); assert.equal(client!.locale, "it-IT"); let calls = 0; const service = new BrandBrainAiService(repo, { OPENAI_API_KEY: "mock", BRAND_BRAIN_AI_ENABLED: true, BRAND_BRAIN_AI_MODEL: "gpt-4.1-mini", BRAND_BRAIN_AI_TIMEOUT_MS: 1000, BRAND_BRAIN_AI_MAX_OUTPUT_TOKENS: 6000 }, async request => { calls++; assert.equal(JSON.parse((request.input[1] as any).content).context.client.id, f.clientId); return { model: request.model, usage: { inputTokens: 123, outputTokens: 45, totalTokens: 168 }, value: { alignmentScore: 70, approvalPrediction: "medium", mainPillar: null, tone: "partial", toneReason: "Memória limitada", audienceFit: "Público não definido", strengths: [], warnings: ["Completar memória"], recommendation: "Revisar", basedOn: ["Voz publicada"] } }; });
    await service.capabilities(f.clientId); assert.equal(calls, 0); await service.analyzePauta(f.clientId, { title: "Teste" }); const [runs] = await f.pool.query<RowDataPacket[]>("SELECT * FROM brand_brain_ai_runs"); assert.equal(runs.length, 1); assert.equal(runs[0].status, "success"); assert.equal(runs[0].total_tokens, 168); assert.equal(runs[0].context_hash.length, 64); assert.doesNotMatch(JSON.stringify(runs), /Publicado|Teste|mock/); const [rows] = await f.pool.query<RowDataPacket[]>("SELECT workspace_drawer_json FROM client_accounts WHERE id=?", [f.clientId]); assert.deepEqual(parsed(rows[0].workspace_drawer_json), f.drawer); assert.equal((await f.pool.query<RowDataPacket[]>("SELECT COUNT(*) AS total FROM kanban_cards"))[0][0].total, 0);
  } finally { await f.close(); }
});
test("MariaDB: existing pauta endpoint adds AI draft once under concurrent retries, preserves edits/full drawer", async () => {
  const f = await fixture(); const app = Fastify(); try { await app.register(httpErrorsPluginRegistered); app.decorate("db", f.pool); app.decorateRequest("auth", null); app.addHook("preHandler", async request => { request.auth = { user: { id: randomUUID(), globalRole: "super_admin", fullName: "Equipe", email: "test@invalid.test", avatarUrl: null, locale: "pt-BR", isActive: true }, memberships: [] }; }); await app.register(clientRoutes, { prefix: "/api" }); const url = `/api/clients/${f.clientId}/workspace-drawer/pauta-ideas`; const idea = { id: randomUUID(), title: "Nova", status: "draft", createdBy: "ai_brand_brain", description: "Descrição", caption: "Legenda", pillar: null, rationale: "Contexto", alignmentScore: 90, basedOn: ["Tom publicado"] };
    const responses = await Promise.all(Array.from({ length: 10 }, () => app.inject({ method: "POST", url, payload: { idea } }))); assert.ok(responses.every(r => r.statusCode === 200)); const edited = await app.inject({ method: "PATCH", url: `${url}/${idea.id}`, payload: { patch: { title: "Edição humana" } } }); assert.equal(edited.statusCode, 200); const retry = await app.inject({ method: "POST", url, payload: { idea } }); assert.equal(retry.json().idea.title, "Edição humana");
    const [rows] = await f.pool.query<RowDataPacket[]>("SELECT workspace_drawer_json FROM client_accounts WHERE id=?", [f.clientId]); const drawer = parsed(rows[0].workspace_drawer_json); assert.equal(drawer.pautaIdeas.length, 2); assert.equal(drawer.pautaIdeas[0].status, "draft"); const { pautaIdeas, ...rest } = drawer; const { pautaIdeas: old, ...expected } = f.drawer; assert.deepEqual(rest, expected); assert.deepEqual(pautaIdeas[1], old[0]); assert.equal((await f.pool.query<RowDataPacket[]>("SELECT COUNT(*) AS total FROM kanban_cards"))[0][0].total, 0); assert.equal((await f.pool.query<RowDataPacket[]>("SELECT COUNT(*) AS total FROM brand_brain_ai_runs"))[0][0].total, 0);
  } finally { await app.close(); await f.close(); }
});
